_core:
  default_config_hash: oDGEkhP0h5rXXqlDplxeBDre0goLigOJupHKMDMwcqM
login_menu_item_title: ''
logout_menu_item_title: ''
login_redirect_url: ''
logout_redirect_url: ''
error_redirect_url: ''
error_throw: false
local_login_saml_error: true
logout_different_user: false
drupal_login_roles:
  authenticated: authenticated
  content_api_consumer: content_api_consumer
  content_editor: content_editor
  content_reviewer: content_reviewer
  content_publisher: content_publisher
  content_admin: content_admin
  redirect_administrator: redirect_administrator
  admnistrator_users: admnistrator_users
  administrator: administrator
  content_creator_benefits_hubs: '0'
  content_creator_resources_and_support: '0'
  office_content_creator: '0'
  vamc_content_creator: '0'
  content_creator_vet_center: '0'
  homepage_manager: '0'
  translation_manager: '0'
sp_entity_id: 'https://prod.cms.va.gov/saml/metadata'
sp_name_id_format: 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified'
sp_x509_certificate: 'file:/certs/cms.va.gov.public.crt'
sp_new_certificate: ''
sp_private_key: 'file:/certs/cms.va.gov.private.key'
metadata_valid_secs: 60
metadata_cache_http: false
idp_entity_id: VA_SSOi_IDP
idp_single_sign_on_service: 'https://logon.iam.va.gov/affwebservices/public/saml2sso'
idp_single_log_out_service: ''
idp_change_password_service: ''
idp_certs:
  - MIIFBTCCA+2gAwIBAgIHPQAAAACnDTANBgkqhkiG9w0BAQsFADBHMRMwEQYKCZImiZPyLGQBGRYDZ292MRIwEAYKCZImiZPyLGQBGRYCdmExHDAaBgNVBAMTE1ZBLUludGVybmFsLVMyLUlDQTQwHhcNMjIxMTAxMTkxMzE1WhcNMjMxMTI1MTkxMzE1WjB2MQswCQYDVQQGEwJVUzERMA8GA1UECBMIVmlyZ2luaWExEDAOBgNVBAcTB0FzaGJ1cm4xJzAlBgNVBAoTHkRlcGFydG1lbnQgb2YgVmV0ZXJhbnMgQWZmYWlyczEZMBcGA1UEAxMQbG9nb24uaWFtLnZhLmdvdjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMELIDluKeYd0eBij0QEjOcypDyvjYTX2klYRNYfVSCKeBctEUycYKBqispUo2H1t98eusdBgjjpAjLmj/dYm7ZQIsPNJHOu+FYW78TketlaPdFBCFr8+YEc1vlA19sEMF81DAWKfaxkg7Q94BdWT8r58aAQcLwAJ8S8vy4qMio3PN/aO3KBMLbQEarYHhbtUIjER8aqfmXtprUMuvmq3M9jHOrnRv//zh5x8hAsm0absaNzFoTWxeiv7WNd22r4nzR50TMiyeRwakjQRPA97S7o1F/fv8GccRcEZCDXj1qbwUWGuBSjVIzt/bVtxo1Do9BGm4e5zzWH2z7RXpINo2ECAwEAAaOCAcUwggHBMBsGA1UdEQQUMBKCEGxvZ29uLmlhbS52YS5nb3YwHQYDVR0OBBYEFIfPO3ByoMw5J8uZxJ6NGkW8GAbTMB8GA1UdIwQYMBaAFGi3comeQurkUUUfWKIKJw9zYECjMEYGA1UdHwQ/MD0wO6A5oDeGNWh0dHA6Ly9jcmwucGtpLnZhLmdvdi9wa2kvY3JsL1ZBLUludGVybmFsLVMyLUlDQTQuY3JsMHgGCCsGAQUFBwEBBGwwajBEBggrBgEFBQcwAoY4aHR0cDovL2FpYS5wa2kudmEuZ292L3BraS9haWEvdmEvVkEtSW50ZXJuYWwtUzItSUNBNC5jZXIwIgYIKwYBBQUHMAGGFmh0dHA6Ly9vY3NwLnBraS52YS5nb3YwDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCBPAwPQYJKwYBBAGCNxUHBDAwLgYmKwYBBAGCNxUIgcjDM4H58AaBpZ8NhOCBCIXCqksGgtrLEYHR8FYCAWQCASswHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMCcGCSsGAQQBgjcVCgQaMBgwCgYIKwYBBQUHAwIwCgYIKwYBBQUHAwEwDQYJKoZIhvcNAQELBQADggEBADztMS8r5aduq1Yr5YL8Sh/1wJeQ7kHAt/MBu8EpoKuhSRv9VxhkvusT27oA4U6htfSpIQQVnZR6T1XzmdexMV1qeNeHhSKZKq9QtCsH94OlLZn8+sqMx9CMI5x+7+adOqxK1yIK7RrDzb4hX6HQZk9fuxoIa1/s5TAMJR5Uui1MBGAJDC0Y3vgLo7d6Bxbk+IA9K3Qe9iEkvnUa4DsgVpDIou+0SycVmAyGDYajqS3K5w055jF9hYLs+vxCleIKf2CMU6Th1m6LyWf3Pn9pdKtfeC2pG68ZqMVik/Zj54uQCCcPAaKzpaLYY51ZsDWLoDJLU8Ah95+ej2ZP14B0ctU=
idp_cert_encryption: ''
unique_id_attribute: VAUID
map_users: false
map_users_name: true
map_users_mail: true
map_users_roles:
  content_creator_benefits_hubs: content_creator_benefits_hubs
  content_creator_resources_and_support: content_creator_resources_and_support
  office_content_creator: office_content_creator
  vamc_content_creator: vamc_content_creator
  content_creator_vet_center: content_creator_vet_center
  content_editor: content_editor
  content_reviewer: content_reviewer
  content_publisher: content_publisher
  content_admin: content_admin
  redirect_administrator: redirect_administrator
  admnistrator_users: admnistrator_users
  administrator: administrator
  homepage_manager: homepage_manager
  translation_manager: translation_manager
  content_api_consumer: '0'
create_users: true
sync_name: true
sync_mail: true
user_name_attribute: adUPN
user_mail_attribute: adUPN
request_set_name_id_policy: true
strict: true
security_metadata_sign: false
security_authn_requests_sign: true
security_logout_requests_sign: false
security_logout_responses_sign: false
security_nameid_encrypt: false
security_signature_algorithm: ''
security_encryption_algorithm: ''
security_messages_sign: false
security_assertions_signed: true
security_assertions_encrypt: true
security_nameid_encrypted: false
security_want_name_id: false
security_request_authn_context: false
security_lowercase_url_encoding: true
security_logout_reuse_sigs: false
security_allow_repeat_attribute_name: false
debug_display_error_details: true
debug_log_in: false
debug_log_saml_in: false
debug_log_saml_out: false
debug_phpsaml: false
use_proxy_headers: false
use_base_url: true
