/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(($, Drupal) => {
  function enforceMaximumNumberOfTags() {
    let total = $('div[id^="edit-field-tags-0-subform-field-topics"]').find("input:checked").length;

    if (total >= 4) {
      $('select[id^="edit-field-tags-0-subform-field-audience-selection"]').attr("disabled", true);
      $("div.form-item-field-tags-0-subform-field-audience-selection").addClass("form-disabled");
    } else {
      $('select[id^="edit-field-tags-0-subform-field-audience-selection"]').attr("disabled", false);
      $("div.form-item-field-tags-0-subform-field-audience-selection").removeClass("form-disabled");
    }

    const audienceSelected = $('div[id^="edit-field-tags-0-subform-field-audience-beneficiares-wrapper"]').find('input:not([id^="edit-field-tags-0-subform-field-audience-beneficiares-none"]):checked').length;
    total += audienceSelected;

    if (total >= 4) {
      $('div[id^="edit-field-tags-0-subform-field-topics"]').find("input[type=checkbox]:not(:checked)").attr("disabled", true);
    } else {
      $('div[id^="edit-field-tags-0-subform-field-topics"]').find("input[type=checkbox]").attr("disabled", false);
    }
  }

  Drupal.behaviors.vaGovAudienceTopics = {
    attach() {
      $("#edit-group-tags > legend").addClass("form-required");

      if ($('select[id^="edit-field-tags-0-subform-field-audience-selection"]').val() !== "beneficiaries") {
        $('div[id^="edit-field-tags-0-subform-field-audience-beneficiares-wrapper"]').hide();
      }

      $('input[id^="edit-field-tags-0-subform-field-audience-beneficiares-none"]').parent().hide();

      $('select[id^="edit-field-tags-0-subform-field-audience-selection"] option[value="non-beneficiaries"]').attr("disabled", true);

      enforceMaximumNumberOfTags();

      $('select[id^="edit-field-tags-0-subform-field-audience-selection"]').change(event => {
        const selection = $(event.currentTarget).val();

        if (selection === "beneficiaries") {
          $('div[id^="edit-field-tags-0-subform-field-audience-beneficiares-wrapper"]').show();
        } else {
          $('input[id^="edit-field-tags-0-subform-field-audience-beneficiares-none"]').prop("checked", true);
          $('div[id^="edit-field-tags-0-subform-field-audience-beneficiares-wrapper"]').hide();
        }

        enforceMaximumNumberOfTags();
      });

      $('div[id^="edit-field-tags-0-subform-field-topics"], div[id^="edit-field-tags-0-subform-field-audience-beneficiares-wrapper"]').find("input").change(() => {
        enforceMaximumNumberOfTags();
      });
    }
  };
})(jQuery, window.Drupal);