/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(function ($, Drupal) {
  Drupal.behaviors.vaGovAudienceTopics = {
    attach: function attach() {
      if ($('div[id^="edit-field-tags-0-subform-field-non-beneficiares-wrapper"]').find('input:not([id^="edit-field-tags-0-subform-field-non-beneficiares-none"]):checked').length) {
        $('select[id^="edit-field-tags-0-subform-field-audience-selection"]').val("non-beneficiaries");
        $('div[id^="edit-field-tags-0-subform-field-non-beneficiares-wrapper"]').show();
        $('div[id^="edit-field-tags-0-subform-field-audience-beneficiares-wrapper"]').hide();
      } else {
        $('select[id^="edit-field-tags-0-subform-field-audience-selection"]').val("beneficiaries");
        $('div[id^="edit-field-tags-0-subform-field-audience-beneficiares-wrapper"]').show();
        $('div[id^="edit-field-tags-0-subform-field-non-beneficiares-wrapper"]').hide();
      }
      $("#edit-group-tags > legend").addClass("form-required");
      $('input[id^="edit-field-tags-0-subform-field-audience-beneficiares-none"]').parent().hide();
      $('input[id^="edit-field-tags-0-subform-field-non-beneficiares-none"]').parent().hide();
      $("fieldset#edit-group-tags").change(function () {
        var selection = $('select[id^="edit-field-tags-0-subform-field-audience-selection"]').val();
        $('fieldset#edit-group-tags input[type="radio"]').attr("checked", false);
        $('div[id^="edit-field-tags-0-subform-field-audience-beneficiares-wrapper"]').hide();
        $('div[id^="edit-field-tags-0-subform-field-non-beneficiares-wrapper"]').hide();
        if (selection === "beneficiaries") {
          $('div[id^="edit-field-tags-0-subform-field-audience-beneficiares-wrapper"]').show();
          $("#edit-field-tags-0-subform-field-non-beneficiares-none").attr("checked", true);
        }
        if (selection === "non-beneficiaries") {
          $('div[id^="edit-field-tags-0-subform-field-non-beneficiares-wrapper"]').show();
          $("#edit-field-tags-0-subform-field-audience-beneficiares-none").attr("checked", true);
        }
        if (selection === "_none") {
          $("#edit-field-tags-0-subform-field-non-beneficiares-none").attr("checked", true);
          $("#edit-field-tags-0-subform-field-audience-beneficiares-none").attr("checked", true);
        }
      });
    }
  };
})(jQuery, window.Drupal);