/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  var fieldTreatments = function fieldTreatments(dom) {
    CKEDITOR.config.autoGrow_onStartup.valueOf = 750;
    var adminRoles = ["administrator"];

    if (drupalSettings.gtm_data.contentType === "centralized_content" && !adminRoles.some(function (item) {
      return drupalSettings.gtm_data.userRoles.includes(item);
    })) {
      Drupal.tableDrag.prototype.hideColumns(1);

      var ccParagraphs = dom.querySelectorAll("div.cc-special-treatment-paragraph.centralized_content_descriptor");

      var wysiParagraphs = dom.querySelectorAll(".draggable.paragraph-type--wysiwyg");

      var wysiParagraphsText = dom.querySelectorAll("div.field--name-field-wysiwyg");

      ccParagraphs.forEach(function (item) {
        if (item && item.parentElement) {
          item.parentElement.classList.add("cc-paragraph-header");
          if (item.parentElement.previousElementSibling) {
            item.parentElement.previousElementSibling.classList.add("cc-paragraph-toggle-remove");
          }
        }
      });

      wysiParagraphs.forEach(function (item) {
        if (item && item.previousElementSibling && item.previousElementSibling.classList.contains("paragraph-type--centralized-content-descriptor")) {
          item.classList.add("cc-national-wysi-padding");
        }
      });

      wysiParagraphsText.forEach(function (item) {
        if (item && item.parentElement.parentElement.parentElement.parentElement.previousElementSibling) {
          item.parentElement.parentElement.parentElement.parentElement.previousElementSibling.classList.add("cc-paragraph-toggle-remove");
        }
      });
    }
  };

  Drupal.behaviors.nationalDataAccessControl = {
    attach: function attach(context) {
      fieldTreatments(context);
    }
  };
})(Drupal);