/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(function (Drupal) {
  function initSelectAllOptions(domNode) {
    var selectAllCheckbox = domNode.querySelector(".select-all-options-checkbox");
    if (!selectAllCheckbox) {
      return;
    }
    var checkboxNodes = domNode.querySelectorAll('input[type="checkbox"]:not(.select-all-options-checkbox)');
    function updateSelectAllState() {
      var count = 0;
      var total = checkboxNodes.length;
      for (var i = 0; i < checkboxNodes.length; i++) {
        if (checkboxNodes[i].checked) {
          count += 1;
        }
      }
      selectAllCheckbox.checked = count === total;
    }
    function setAllCheckboxes(value) {
      for (var i = 0; i < checkboxNodes.length; i++) {
        checkboxNodes[i].checked = value;
      }
      updateSelectAllState();
    }
    function onSelectAllChange(event) {
      setAllCheckboxes(event.target.checked);
    }
    function onCheckboxChange() {
      updateSelectAllState();
    }
    selectAllCheckbox.addEventListener("change", onSelectAllChange);
    for (var i = 0; i < checkboxNodes.length; i++) {
      checkboxNodes[i].addEventListener("change", onCheckboxChange);
    }
    updateSelectAllState();
  }
  Drupal.behaviors.selectAllOptions = {
    attach: function attach(context) {
      var containers = context.querySelectorAll(".select-all-mixed");
      for (var i = 0; i < containers.length; i++) {
        initSelectAllOptions(containers[i].parentNode);
      }
    }
  };
})(Drupal);