/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(Drupal => {
  Drupal.behaviors.vaGovContactParagraphsInteractions = {
    attach(context) {
      const extensionFieldsSelects = context.querySelectorAll(".field--name-field-phone-number-type select");
      extensionFieldsSelects.forEach(ext => {
        ext.addEventListener("change", () => {
          const divWrap = ext.parentElement.parentElement.parentElement;
          const extInput = divWrap.querySelector(".field--name-field-phone-extension");

          if (ext.value === "tel") {
            extInput.style.display = "block";
          } else {
            extInput.style.display = "none";
          }
        });
      });
    }
  };
})(Drupal);