/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  var includeRegistrationsBool = document.getElementById("edit-field-include-registration-info-value");

  var toggleRegistrationElements = function toggleRegistrationElements() {
    var targetRegistrationElements = document.querySelectorAll(".centralized.reduced-padding, #edit-field-event-registrationrequired-wrapper, #edit-group-registration-link");
    var toggleVal = !!includeRegistrationsBool.checked;
    targetRegistrationElements.forEach(function (element) {
      if (toggleVal) {
        element.style.display = "block";
      } else {
        element.style.display = "none";
      }
    });
  };

  var includeLocationItemsRadios = document.getElementById("edit-field-location-type");

  var toggleLocationElements = function toggleLocationElements() {
    var targetLocationElements = document.querySelectorAll("#edit-field-facility-location-wrapper, #edit-field-url-of-an-online-event-wrapper, #edit-field-location-humanreadable-wrapper, #edit-field-address-wrapper");
    targetLocationElements.forEach(function (element) {
      element.style.display = "none";
    });
    if (document.getElementById("edit-field-location-type-facility").checked) {
      document.getElementById("edit-field-facility-location-wrapper").style.display = "block";
      document.getElementById("edit-field-location-humanreadable-wrapper").style.display = "block";
    }
    if (document.getElementById("edit-field-location-type-non-facility").checked) {
      document.getElementById("edit-field-address-wrapper").style.display = "block";
    }
    if (document.getElementById("edit-field-location-type-online").checked) {
      document.getElementById("edit-field-url-of-an-online-event-wrapper").style.display = "block";
    }
  };

  var operate = function operate() {
    includeRegistrationsBool.addEventListener("click", function () {
      toggleRegistrationElements();
    });
    toggleRegistrationElements();

    includeLocationItemsRadios.addEventListener("change", function () {
      toggleLocationElements();
    });
    toggleLocationElements();
  };

  Drupal.behaviors.vaGovEventFormHelpers = {
    attach: function attach() {
      window.addEventListener("DOMContentLoaded", operate(document));
    }
  };
})(Drupal);