/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  var alterHelpTextLocationOnDateField = function alterHelpTextLocationOnDateField(items) {
    if (items.length > 0) {
      items.forEach(function (item) {
        if (item.previousElementSibling !== null && item.previousElementSibling.previousElementSibling !== null && item.previousElementSibling.previousElementSibling.nodeName === "H4") {
          item.previousElementSibling.previousElementSibling.after(item);
          item.style.margin = "0 0 10px 0px";
        }
      });
    }
  };

  var alterHelpTextLocationOnTextField = function alterHelpTextLocationOnTextField(items) {
    if (items.length > 0) {
      items.forEach(function (item) {
        if (item.previousElementSibling !== null && item.previousElementSibling.previousElementSibling !== null && item.previousElementSibling.previousElementSibling.nodeName === "LABEL") {
          item.previousElementSibling.previousElementSibling.after(item);
          item.style.margin = "0 0 10px 0px";
        }
      });
    }
  };

  var alterHelpTextLocationOnLongTextPlainField = function alterHelpTextLocationOnLongTextPlainField(items) {
    if (items.length > 0) {
      items.forEach(function (item) {
        if (item.previousElementSibling !== null && item.previousElementSibling.previousElementSibling !== null && item.previousElementSibling.previousElementSibling.previousElementSibling !== null && item.previousElementSibling.previousElementSibling.previousElementSibling.nodeName === "LABEL") {
          item.previousElementSibling.previousElementSibling.previousElementSibling.after(item);
          item.style.margin = "0 0 10px 0px";
        }
      });
    }
  };

  var alterHelpTextLocationOnLongTextFullHtmlField = function alterHelpTextLocationOnLongTextFullHtmlField(items) {
    if (items.length > 0) {
      items.forEach(function (item) {
        if (item.previousElementSibling !== null && item.previousElementSibling.previousElementSibling !== null && item.previousElementSibling.previousElementSibling.firstElementChild !== null && item.previousElementSibling.previousElementSibling.firstElementChild.nodeName === "LABEL") {
          item.previousElementSibling.previousElementSibling.firstElementChild.after(item);
          item.style.margin = "0 0 10px 0px";
        }
      });
    }
  };

  var alterHelpTextLocationOnParagraphsExperimentalWidget = function alterHelpTextLocationOnParagraphsExperimentalWidget(items) {
    if (items.length > 0) {
      items.forEach(function (item) {
        if (item.previousElementSibling !== null && item.previousElementSibling.firstElementChild !== null && item.previousElementSibling.firstElementChild.firstElementChild !== null && item.previousElementSibling.firstElementChild.firstElementChild.firstElementChild.firstElementChild !== null && item.previousElementSibling.firstElementChild.firstElementChild.firstElementChild.firstElementChild.nodeName === "H4") {
          item.style.fontWeight = "400";
          item.style.textTransform = "none";
          item.style.margin = "0 0 10px 0px";
          item.previousElementSibling.firstElementChild.firstElementChild.firstElementChild.firstElementChild.after(item);
        }
      });
    }
  };

  Drupal.behaviors.vaGovtextContentDescriptionPlacement = {
    attach: function attach(context) {
      var textareaDescriptions = context.querySelectorAll(".description");
      alterHelpTextLocationOnDateField(textareaDescriptions);
      alterHelpTextLocationOnTextField(textareaDescriptions);
      alterHelpTextLocationOnLongTextPlainField(textareaDescriptions);
      alterHelpTextLocationOnLongTextFullHtmlField(textareaDescriptions);
      alterHelpTextLocationOnParagraphsExperimentalWidget(textareaDescriptions);
    }
  };
})(Drupal);