/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  var myFacility = "";

  var adminField = document.getElementById("edit-field-administration");
  var adminFieldOptions = document.querySelectorAll("#edit-field-administration option");

  var facilityFieldOptions = document.querySelectorAll("#edit-field-facility-location option");
  var systemFieldOptions = document.querySelectorAll("#edit-field-regional-health-service option");
  var facilityField = document.getElementById("edit-field-facility-location");
  var systemField = document.getElementById("edit-field-regional-health-service");
  var lovellVaPattern = /Lovell.*VA/i;
  var lovellTricarePattern = /Lovell.*TRICARE/i;
  var winnower = function winnower() {
    var pathType = drupalSettings.path.currentPath.split("/")[1];

    if (typeof facilityField !== "undefined" && facilityField !== null && pathType === "add") {
      facilityField.selectedIndex = "_none";
    }
    if (typeof systemField !== "undefined" && systemField !== null && pathType === "add") {
      systemField.selectedIndex = "_none";
    }

    var adminFieldText = adminField.options[adminField.selectedIndex].text;

    var adminMatcher = void 0;
    if (adminFieldText.search(lovellTricarePattern) > -1) {
      adminMatcher = "Lovell Federal TRICARE health care";
    } else if (adminFieldText.search(lovellVaPattern) > -1) {
      adminMatcher = "Lovell Federal VA health care";
    } else {
      adminMatcher = adminFieldText.replace(/(^-+)/g, "");
    }

    function hideSeekShow(domElement) {
      domElement.forEach(function (i) {
        i.classList.add("hidden-option");
        if (i.text.includes(adminMatcher)) {
          i.classList.remove("hidden-option");
        }
      });
    }

    hideSeekShow(facilityFieldOptions);
    hideSeekShow(systemFieldOptions);

    function seekHide(domElement, match) {
      domElement.forEach(function (i) {
        if (i.text.includes(match)) {
          i.classList.add("hidden-option");
        }
      });
    }

    seekHide(adminFieldOptions, "Lovell Federal health care");
  };

  Drupal.behaviors.vaGovLimitServiceOptions = {
    attach: function attach() {
      if (myFacility === "" || window.onload) {
        winnower();
      }
      adminField.addEventListener("change", winnower);
      if (facilityField !== null) {
        facilityField.addEventListener("change", function setText() {
          myFacility = facilityField.options[facilityField.selectedIndex].text;
        });
      }
    }
  };
})(Drupal);