/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.vaGovMediaLibraryReusableSaveAndSelect = {
    attach: function attach() {
      $(document).ajaxComplete(function () {
        $("input.field_media_in_library[type=checkbox]:not(:checked)").each(function () {
          $(".ui-dialog-buttonpane button").first().hide();
        });
        $("input.field_media_in_library").once().change(function (object) {
          if (object.checked) {
            $(".ui-dialog-buttonpane button").first().show();
          } else {
            $(".ui-dialog-buttonpane button").first().hide();
          }
        });
      });
    }
  };
})(jQuery, window.Drupal);