/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.vaGovTooltip = {
    attach: function attach() {
      var addTooltip = [];

      $('div[id*="add-tooltip--"]').each(function (tt, element) {
        addTooltip.push($(element).attr("id"));
      });

      function prepareTooltip(value) {
        $("#" + value).once("vaGovTooltip").each(function () {
          $("#" + value).before($("<div class=\"tooltip-toggle " + value + " \"><button class=\"toggle-a\"></button></div>"));
          $("#" + value).attr("class", "addTooltip");
        });
      }

      function engageTooltip(value) {
        $("." + value).once("vaGovTooltip").on("focusin focusout mouseenter mouseleave", function () {
          $("#" + value).toggle();
        });
      }

      $.each(addTooltip, function (key, value) {
        prepareTooltip(value);
        engageTooltip(value);
      });
    }
  };

  Drupal.behaviors.vaGovClpLimitListOfLinks = {
    attach: function attach() {
      if ($("#field-clp-spotlight-link-teasers-add-more-wrapper .paragraphs-dropbutton-wrapper").length > 3) {
        $("#field-clp-spotlight-link-teasers-add-more-wrapper .field-add-more-submit.button--small.button").css("display", "none");
      }
    }
  };

  Drupal.behaviors.vaGovAlertSingleComponent = {
    attach: function attach() {
      var reusableAlertRemovedIds = [];
      var reusableAlertAddedIds = [];
      var nonReusableAlertAddedIds = [];
      var nonReusableAlertSelectionIds = [];

      $('input[id*="subform-field-alert-block-reference-entity-browser-entity-browser-open-modal"]').each(function (idx, element) {
        reusableAlertRemovedIds.push($(element).attr("id"));
      });

      $('div[id*="field-alert-block-reference-current-items-0"]').each(function (idx, element) {
        reusableAlertAddedIds.push($(element).attr("id"));
      });

      $('fieldset[id*="subform-group-n"]').each(function (idx, element) {
        nonReusableAlertAddedIds.push($(element).attr("id"));
      });

      $.each(reusableAlertRemovedIds, function (key, value) {
        var y = $("#" + value).parents(".paragraphs-subform").children(".field--name-field-alert-selection").find(".fieldset-wrapper").children().attr("id");
        $("#" + y + "> div > input").each(function (idx, element) {
          $(element).prop("disabled", false);
        });
      });

      $.each(reusableAlertAddedIds, function (key, value) {
        var x = $("#" + value).parents(".paragraphs-subform").children(".field--name-field-alert-selection").find(".fieldset-wrapper").children().attr("id");

        $("#" + x + "> div > input").each(function (idx, element) {
          $(element).prop("disabled", true);
        });
      });

      $.each(nonReusableAlertAddedIds, function (key, value) {
        nonReusableAlertSelectionIds.push($("#" + value).closest("div[id*='subform-field-alert-wrapper'],div[id*='alert-single-wrapper']").find(".paragraphs-subform").first().children(".field--name-field-alert-selection").children().children(".fieldset-wrapper").children().attr("id"));

        $.each(nonReusableAlertSelectionIds, function (sectionKey, sectionValue) {
          $("#" + sectionValue + "> div > input").each(function (idx, element) {
            $(element).prop("disabled", true);
          });
        });
      });
    }
  };

  Drupal.behaviors.vaGovRequiredParagraphs = {
    attach: function attach() {
      $("details#edit-field-clp-resources summary").addClass("js-form-required form-required");
      $("details#edit-field-clp-events-references summary").addClass("js-form-required form-required");
      $("details#edit-group-video .field--type-entity-reference.field--name-field-media span.fieldset-legend").addClass("js-form-required form-required");
      $("#edit-field-clp-stories-teasers-wrapper").attr({
        required: "required",
        "aria-required": "true"
      });
      $("#edit-field-clp-stories-teasers-wrapper strong").addClass("form-required");
    }
  };
})(jQuery, window.Drupal);