/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(function (Drupal) {
  function initSelectAllOptions(domNode) {
    var selectAllCheckbox = domNode.querySelector(".select-all-options-checkbox");
    if (!selectAllCheckbox) {
      return;
    }
    selectAllCheckbox.setAttribute("role", "checkbox");
    selectAllCheckbox.setAttribute("aria-checked", "false");
    selectAllCheckbox.setAttribute("tabindex", "0");
    var checkboxNodes = domNode.querySelectorAll('input[type="checkbox"]:not(.select-all-options-checkbox)');
    function updateSelectAllState() {
      var count = 0;
      var total = checkboxNodes.length;
      for (var i = 0; i < checkboxNodes.length; i++) {
        if (checkboxNodes[i].checked) {
          count += 1;
        }
      }
      if (count === 0) {
        selectAllCheckbox.checked = false;
        selectAllCheckbox.indeterminate = false;
        selectAllCheckbox.setAttribute("aria-checked", "false");
      } else if (count === total) {
        selectAllCheckbox.checked = true;
        selectAllCheckbox.indeterminate = false;
        selectAllCheckbox.setAttribute("aria-checked", "true");
      } else {
        selectAllCheckbox.checked = true;
        selectAllCheckbox.indeterminate = true;
        selectAllCheckbox.setAttribute("aria-checked", "mixed");
      }
    }
    function setAllCheckboxes(value) {
      for (var i = 0; i < checkboxNodes.length; i++) {
        checkboxNodes[i].checked = value;
      }
      updateSelectAllState();
    }
    function onSelectAllChange(event) {
      var checked = event.target.checked;
      setAllCheckboxes(checked);
    }
    function onCheckboxChange() {
      updateSelectAllState();
    }
    function onKeydown(event) {
      if (event.key === " ") {
        event.preventDefault();
      }
    }
    function onKeyup(event) {
      if (event.key === " ") {
        event.preventDefault();
        selectAllCheckbox.checked = !selectAllCheckbox.checked;
        setAllCheckboxes(selectAllCheckbox.checked);
      }
    }
    function onFocus() {
      selectAllCheckbox.classList.add("focus");
    }
    function onBlur() {
      selectAllCheckbox.classList.remove("focus");
    }
    selectAllCheckbox.addEventListener("change", onSelectAllChange);
    selectAllCheckbox.addEventListener("keydown", onKeydown);
    selectAllCheckbox.addEventListener("keyup", onKeyup);
    selectAllCheckbox.addEventListener("focus", onFocus);
    selectAllCheckbox.addEventListener("blur", onBlur);
    for (var i = 0; i < checkboxNodes.length; i++) {
      checkboxNodes[i].addEventListener("change", onCheckboxChange);
    }
    updateSelectAllState();
  }
  Drupal.behaviors.selectAllOptions = {
    attach: function attach(context) {
      var containers = context.querySelectorAll(".select-all-options");
      for (var i = 0; i < containers.length; i++) {
        initSelectAllOptions(containers[i].parentNode);
      }
    }
  };
})(Drupal);