/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  Drupal.behaviors.vaGovServiceLocationAddress = {
    attach: function attach() {
      var checkboxes = document.querySelectorAll(".paragraph-type--service-location-address .form-checkbox");
      checkboxes.forEach(function (check) {
        var address = check.parentElement.parentElement.nextElementSibling;
        check.addEventListener("click", function () {
          if (check.checked) {
            address.style.display = "none";
          } else {
            address.style.display = "block";
          }
        });
      });
    }
  };
})(Drupal);