/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  var displayHours = function displayHours(toggle, table) {
    if (toggle.value === "2") {
      table.style.display = "block";
    } else {
      table.style.display = "none";
    }
  };

  Drupal.behaviors.vaGovServiceLocationHours = {
    attach: function attach() {
      var hourSelects = document.querySelectorAll(".field--name-field-hours select");
      hourSelects.forEach(function (hourSelect) {
        var hours = hourSelect.parentElement.parentElement.nextElementSibling;

        window.addEventListener("load", function () {
          displayHours(hourSelect, hours);
        });

        hourSelect.addEventListener("change", function () {
          displayHours(hourSelect, hours);
        });
      });
    }
  };
})(Drupal);