/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.vaGovServiceLocationAddress = {
    attach: function attach(context) {
      function addressRequired(address, action) {
        address.find(".form-item label").not(".visually-hidden").each(function cycleAddress() {
          if (action === "yes") {
            $(this).addClass("js-form-required form-required");
            $(this).next("input, select").addClass("required").attr("required", "required");
          } else {
            $(this).removeClass("js-form-required form-required");
            $(this).next("input, select").removeClass("required").removeAttr("required");
          }
        });
      }

      $(".paragraph-type--service-location-address .form-checkbox").each(function cycleCheckbox() {
        var $address = $(this).parent().parent().next(".field--type-address");

        if ($(this).prop("checked")) {
          $address.css("display", "none");
          addressRequired($address, "no");
        } else {
          $address.css("display", "block");
          addressRequired($address, "yes");
        }

        $(this).on("change", function onChange() {
          if ($(this).prop("checked")) {
            $address.css("display", "none");
            addressRequired($address, "no");
          } else {
            $address.css("display", "block");
            addressRequired($address, "yes");
          }
        });
      });

      var serviceLocations = context.querySelectorAll(".paragraph-type--service-location");
      var serviceLocationsToggles = context.querySelectorAll(".paragraph-type--service-location .paragraphs-dropdown-toggle");

      if (serviceLocations.length < 2) {
        serviceLocationsToggles.forEach(function (item) {
          item.style.display = "none";
        });
      }
    }
  };
})(jQuery, Drupal);