/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  Drupal.behaviors.vaGovSetMenuTitle = {
    attach: function attach() {
      var bodyWysiwygLabel = document.querySelector('label[for="edit-field-body-0-value"]');

      bodyWysiwygLabel.classList.add("js-form-required", "form-required");
    }
  };
})(Drupal);