/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };

(function (Drupal) {
  Drupal.behaviors.smartDateInteractions = {
    attach: function attach() {
      var timeEnd = document.querySelector(".time-end");

      if (timeEnd !== null && (typeof timeEnd === "undefined" ? "undefined" : _typeof(timeEnd)) === "object") {
        var alldayLabels = document.querySelectorAll(".allday-label");

        alldayLabels.forEach(function (label) {
          label.style.display = "none";
          label.classList.add("hidden");
        });
      }
    }
  };
})(Drupal);