/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, Tippy) {
  Drupal.behaviors.vaGovToolbar = {
    attach: function attach() {
      Tippy("#ajax-tippy", {
        content: "Loading...",
        flipOnUpdate: true
      });
    }
  };
})(jQuery, window.Drupal, window.tippy);