/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.vaGovToolbar = {
    attach: function attach() {
      $(".toolbar-icon-content-release").once("vaGovToolbar").click(function () {
        $(".toolbar-icon-content-release").toggleClass("show-tooltip");
      });
    }
  };
})(jQuery, window.Drupal);