<?php

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Alter bundle field definitions.
 *
 * Implements hook_entity_bundle_field_info_alter.
 *
 * @param \Drupal\Core\Field\FieldDefinitionInterface[] $fields
 *   The array of bundle field definitions.
 * @param \Drupal\Core\Entity\EntityTypeInterface $entity_type
 *   The entity type definition.
 * @param string $bundle
 *   The bundle.
 */

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function va_gov_magichead_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle): void {
  if (!empty($fields['field_va_benefit_eligibility'])) {
    $fields['field_va_benefit_eligibility']->addConstraint('MagicheadDepthFieldConstraint', []);
  }

}
