<?php

/**
 * @file
 * Contains va_gov_access.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function va_gov_access_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $perms = \Drupal::service('va_gov_services.user_perms');
  $targets = ['field_office'];
  foreach ($targets as $target) {
    if (in_array('field_office', $form)) {
      foreach ($form[$target]['widget']['#options'] as $header_key => $option_header) {
        foreach ($option_header as $option_key => $option_item) {
          $status = $perms->userAccess($option_key, 'node');
          if ($status === FALSE) {
            unset($form[$target]['widget']['#options'][$header_key][$option_key]);
          }
        }
      }
    }
  }

}
