/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  Drupal.behaviors.vaGovTextFieldTooltips = {
    attach: function attach(context) {
      var tooltipFactory = function tooltipFactory(toolTipText, placementTarget) {
        if (context === document) {
          var target = context.getElementById("edit-" + placementTarget);
          var disabledClass = target.disabled ? "disabled-input" : "enabled-input";
          var nameButtonContainerDiv = context.createElement("div");
          var nameButton = context.createElement("button");
          nameButtonContainerDiv.className = "tooltip-container-div name-button-container-div " + disabledClass;
          nameButton.className = "css-tooltip-toggle";
          nameButton.value = toolTipText;
          nameButton.type = "button";
          nameButton.ariaLabel = "tooltip";
          nameButton.setAttribute("data-tippy", toolTipText);
          nameButton.setAttribute("data-tippy-pos", "right");
          nameButton.setAttribute("data-tippy-animate", "fade");
          nameButton.setAttribute("data-tippy-size", "large");
          nameButtonContainerDiv.appendChild(nameButton);
          target.after(nameButtonContainerDiv);
        }
      };

      var targets = [{
        text: "Why can’t I edit this?\nThis content is automatically populated from centralized databases, and helps maintain consistent information across all of VA.gov.",
        element: "field-official-name-0-value"
      }, {
        text: "Why can’t I edit this?\nThe common name is set up to keep a consistent format with other Vet Centers across all of VA.gov.",
        element: "title-0-value"
      }];

      targets.forEach(function (target) {
        tooltipFactory(target.text, target.element);
      });
    }
  };
})(Drupal);