version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
    timezone: US/Eastern
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: acquia/drupal-spec-tool
    versions:
    - ">= 3.a"
    - "< 4"
  - dependency-name: bower-asset/dropzone
    versions:
    - ">= 5.7.a"
    - "< 5.8"
  - dependency-name: drupal/admin_toolbar
    versions:
    - ">= 2.a"
    - "< 3"
  - dependency-name: drupal/linkit
    versions:
    - ">= 6.a"
    - "< 7"
  - dependency-name: drupal/rest_menu_tree
    versions:
    - ">= 2.a"
    - "< 3"
  - dependency-name: drupal/uswds
    versions:
    - ">= 2.a"
    - "< 3"
  - dependency-name: drupal/views_bulk_operations
    versions:
    - ">= 3.a"
    - "< 4"
  - dependency-name: drush/drush
    versions:
    - ">= 10.a"
    - "< 11"
  - dependency-name: ezyang/htmlpurifier
    versions:
    - ">= 4.13.a"
    - "< 4.14"
  - dependency-name: myclabs/deep-copy
    versions:
    - ">= 1.10.a"
    - "< 1.11"
  - dependency-name: symfony/browser-kit
    versions:
    - "> 4.4.3"
    - "< 4.5"
  - dependency-name: symfony/config
    versions:
    - ">= 4.a"
    - "< 5"
  - dependency-name: symfony/finder
    versions:
    - ">= 4.a"
    - "< 5"
  - dependency-name: symfony/phpunit-bridge
    versions:
    - "> 5.1.2"
    - "< 5.2"
  - dependency-name: symfony/validator
    versions:
    - "> 3.4.42"
    - "< 3.5"
  - dependency-name: webmozart/assert
    versions:
    - "> 1.9.0"
    - "< 1.10"
  rebase-strategy: disabled
