# This file is needed for us to customize what devshop does.
#
# It can be removed once devshop supports yaml-tests natively.

deploy: |
  composer yaml-tests --tests-file=deploy.yml --ansi

test: |
  echo "Running `composer yaml-tests` on tests.yml..."
  composer yaml-tests --tests-file=tests.yml --ansi
