name: va-gov-cms
recipe: drupal8
config:
  webroot: docroot
  php: "7.2"
  drush: path:/app/docroot/vendor/bin/drush

events:
  # Clear caches after a database import
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cr -y

  # Runs composer install after app starts
  post-start:
    - appserver: cd $LANDO_MOUNT && composer install

  # After code changes
  post-update:
    - appserver: cd $LANDO_MOUNT && composer install
    - appserver: cd $LANDO_WEBROOT && drush updb -y &&  drush cr -y

services:
  appserver:
    run_as_root:
      - "apt-get update -y"
      - "apt-get install build-essential chrpath libssl-dev libxft-dev libfreetype6-dev libfreetype6 libfontconfig1-dev libfontconfig1 -y"
      - "tar xvjf /app/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /usr/local/share/"
      - "mv /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/bin/"
      - "cd /usr/bin"
      - "chmod +x phantomjs"
    # Uncomment the below `xdebug: true` for Xdebug support
    # @todo Change this to pull in a local Lando settings variable and use that boolean variable
    # Run `lando rebuild` after uncommenting
    #xdebug: true
    overrides:
      services:
        environment:
          # Support debugging Drush with XDEBUG. Listen in PHPStorm then `lando drush` to trigger xdebug.
          PHP_IDE_CONFIG: "serverName=appserver"
  node:
    type: node
    build:
      - "cd $LANDO_MOUNT/docroot/themes/custom/vagov && npm install"
    overrides:
      services:
        environment:
          BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://vagovcms.lndo.site/"}, "Drupal\\DrupalExtension" : {"drush" : { "root": "/app/docroot" }}}}'
      ports:
        - 3000:3000
        - 3001:3001
      image: node:10.13-jessie

    globals:
      gulp-cli: "latest"
tooling:
  phantomjs:
    service: appserver
    description: "Run phantomjs commands"
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit. Syntax: lando phpunit {PATH-TO-TEST}"
    cmd: /app/docroot/vendor/bin/phpunit --bootstrap=/app/docroot/vendor/weitzman/drupal-test-traits/src/bootstrap.php -c /app
  behat:
    service: appserver
    description: "Run behat tests locally. Run from /tests dir."
    cmd:
      - /app/docroot/vendor/bin/behat
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
