runner:
  phpstan:
    name: phpstan
    cmd: /bin/bash -lc 'phpstan analyze docroot/modules/custom/
    level: warning
    format: phpstan
  phpcs:
    name: phpcs
    cmd: /bin/bash -lc 'phpcs docroot/modules/custom/ --report-checkstyle'
    level: warning
    format: checkstyle
