runner:
  phpstan:
    name: phpstan
    cmd: phpstan analyze docroot/modules/custom/ --error-format=checkstyle
    level: warning
    format: checkstyle
  phpcs:
    name: phpcs
    cmd: phpcs docroot/modules/custom/ --report-checkstyle
    level: warning
    format: checkstyle
