FROM devwithlando/php:7.2-apache

RUN apt-get update -y \
  && docker-php-ext-install pcntl

# Load vagov trusted certs
COPY docker/config/certs/vagov-trusted-ca.pem /tmp/
RUN cat /tmp/vagov-trusted-ca.pem >> /etc/ssl/certs/ca-certificates.crt

RUN mkdir /var/www/.drush
RUN mkdir /var/www/.drupal
COPY docker/config/services/config/php/php.ini /usr/local/etc/php/conf.d/xxx-lando-default.ini
COPY docker/config/services/config/php/httpd-ssl.conf /etc/apache2/sites-enabled/000-default.conf
COPY docker/config/services/config/drupal8/php.ini /usr/local/etc/php/conf.d/zzz-lando-my-custom-ini-file-called-php.ini
COPY docker/config/engine/scripts/lando-entrypoint-app.sh /lando-entrypoint.sh
COPY docker/config/engine/scripts/check-health-cms-service.sh /check-health-cms-service.sh
COPY docker/config /lando
COPY docker/config/engine/scripts/user-perms.sh /helpers/user-perms.sh
COPY docker/config/engine/scripts/add-cert.sh /scripts/add-cert.sh
COPY docker/config/engine/scripts/load-keys.sh /scripts/load-keys.sh
COPY docker/config/services/helpers/sql-import.sh /helpers/sql-import.sh
COPY docker/config/services/helpers/sql-export.sh /helpers/sql-export.sh
COPY docker/config/engine/scripts/wait-for-it.sh /usr/bin/wait-for-it.sh
COPY . /app

# Custom vagovcms settings
RUN apt-get update -y
RUN apt-get install python-pip -y
RUN pip install j2cli
RUN mkdir /templates
COPY docker/templates/* /templates/
# @see .composer-cache/README.md & https://stackoverflow.com/a/46801962/292408
COPY .composer-cache/README.md .composer-cache/composer-cache* /tmp/
# Hack to only run composer install if no matching cache was downloaded.
RUN if [ -f /tmp/composer-cache*.tar.gz ]; then cd /app && tar --extract --gzip --file /tmp/composer-cache*.tar.gz; else cd /app && composer install; fi
