FROM mysql:5.7

COPY docker/config/services/config/drupal8/mysql /etc/mysql/conf.d
COPY docker/config/engine/scripts/lando-entrypoint.sh /lando-entrypoint.sh
COPY . /app
COPY docker/config /lando
COPY drupal8.headless.gz /docker-entrypoint-initdb.d/dump.sql.gz
COPY docker/config/engine/scripts/user-perms.sh /helpers/user-perms.sh
COPY docker/config/engine/scripts/add-cert.sh /scripts/add-cert.sh
COPY docker/config/engine/scripts/load-keys.sh /scripts/load-keys.sh
COPY docker/config/services/helpers/sql-import.sh /helpers/sql-import.sh
COPY docker/config/services/helpers/sql-export.sh /helpers/sql-export.sh
