site_name: 'VA.gov CMS Developer Documentation'
site_description: 'How to build applications using the VA.gov Content Management System.'
repo_url: 'https://github.com/department-of-veterans-affairs/va.gov-cms'
edit_uri: edit/main/READMES/

nav:
  - Home: README.md

plugins:
  - techdocs-core
