import colors from "./sb-color-overrides.twig";

// These are our design system tokens, generated by `yarn css`
import customProperties from "../../.storybook/cssVariables.json";

const vars = customProperties["custom-properties"];

// Filter the CSS properties we want for a given Story
const colorVars = Object.keys(vars)
  .filter(
    (key) =>
      key.includes("--color-") ||
      key.includes("--button-") ||
      key.includes("--input")
  )
  .reduce((obj, key) => {
    if (vars[key].toLowerCase().matchAll("#", "var")) {
      obj[key] = vars[key];
    }
    return obj;
  }, {});

export default { title: "Design System Tokens" };

export const ColorOverrides = {
  args: {
    vars: colorVars,
  },
  parameters: {
    options: { showPanel: false }
  },
  argTypes: {
    vars: {
      table: { disable: true }
    }
  }
}

ColorOverrides.parameters.render = async (args) => {
  return await colors({ ...ColorOverrides.args, ...args });
};
