/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

const gulp = require("gulp");
const sass = require("gulp-sass");
const autoprefixer = require("gulp-autoprefixer");
const sourcemaps = require("gulp-sourcemaps");

const { spawn } = require("child_process");

gulp.task("sass", () => {
  return gulp.src(["assets/scss/**/*.scss"]).pipe(sourcemaps.init()).pipe(sass({ outputStyle: "compressed" }).on("error", sass.logError)).pipe(autoprefixer("last 2 version")).pipe(sourcemaps.write("./")).pipe(gulp.dest("assets/css/"));
});
gulp.task("sass").description = "process SCSS files: compile to compressed css, add browser prefixes, create a source map, and save in assets folder";

gulp.task("clearcache", done => {
  const child = spawn("lando drush cache-rebuild", {
    stdio: "inherit",
    shell: "true"
  });
  child.on("close", done);
});
gulp.task("clearcache").description = "clear all Drupal caches";

gulp.task("watch", () => {
  gulp.watch(["scss/**/*.scss"], gulp.series("sass"));
});
gulp.task("watch").description = "watch SCSS";

gulp.task("default", gulp.series("sass"));
gulp.task("default").description = "process SCSS, watch SCSS files for changes.";