/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  var adminFieldOptions = document.querySelectorAll("#edit-field-administration option");
  var vamcSystemFieldOptions = document.querySelectorAll("#edit-field-region-page option");

  function seekHide(domElement, match) {
    domElement.forEach(function (i) {
      if (i.text.includes(match)) {
        i.classList.add("hidden-option");
      }
    });
  }

  var lovellRemover = function lovellRemover() {
    var adminMatcher = "Lovell Federal health care";
    if (adminFieldOptions) {
      seekHide(vamcSystemFieldOptions, adminMatcher);
    }
    if (vamcSystemFieldOptions) {
      seekHide(adminFieldOptions, adminMatcher);
    }
  };

  Drupal.behaviors.vaGovRemoveLovellFederal = {
    attach: function attach() {
      lovellRemover();
    }
  };
})(Drupal);