/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.vaGovWinnowServiceNamesForTricare = {
    attach: function attach(context) {
      Drupal.isTricareSystem = function (subcontext) {
        var tricareSystem = false;
        var vamcSystemSelector = subcontext.getElementById("edit-field-region-page");
        if (vamcSystemSelector !== null) {
          var tricareSystemId = "49011";
          if (vamcSystemSelector.value === tricareSystemId) {
            tricareSystem = true;
          }
        }
        return tricareSystem;
      };

      var winnowTricareServices = function winnowTricareServices(options) {
        if (options && options.length > 0) {
          var tricareSystem = Drupal.isTricareSystem(context);

          options.forEach(function (option) {
            if (!tricareSystem && option.text.includes("(TRICARE)") || tricareSystem && option.text.toLowerCase().includes("vet")) {
              option.classList.add("hidden-option");
            } else {
              option.classList.remove("hidden-option");
            }
          });
        }
      };

      window.addEventListener("DOMContentLoaded", function () {
        var systemSelect = context.getElementById("edit-field-region-page");
        if (systemSelect !== null) {
          systemSelect.addEventListener("change", function () {
            winnowTricareServices(context.querySelectorAll(".field--name-field-service-name-and-descripti select option"));
          });
          winnowTricareServices(context.querySelectorAll(".field--name-field-service-name-and-descripti select option"));
        }
      });
    }
  };
})(jQuery, Drupal);