/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  Drupal.behaviors.vaGovAlertBlockTreatment = {
    attach: function attach() {
      var alertType = document.getElementById("edit-field-is-this-a-header-alert-");

      var scopeContainer = document.getElementById("edit-field-node-reference-wrapper");
      alertType.addEventListener("change", function () {
        scopeContainer.style.display = "block";
        if (alertType.value !== "banner_alert") {
          scopeContainer.style.display = "none";
        }
      });
      window.addEventListener("DOMContentLoaded", function () {
        scopeContainer.style.display = "block";
        if (alertType.value !== "banner_alert") {
          scopeContainer.style.display = "none";
        }
      });
    }
  };
})(Drupal);