user.role.*.third_party.va_gov_backend:
  type: mapping
  label: 'Description'
  mapping:
    vgb_description:
      type: text
      label: 'Desciption'
field.widget.settings.tooltip_textfield:
  type: mapping
  label: 'Textfield tooltip widget settings'
  mapping:
    tooltip_text:
      type: text
      label: 'Tooltip text'
