#!/bin/bash

echo -e "
******************************ATTN*******************************
* IMPORTANT: The default master branch will be renamed to main! *
* This will happen 11/3/2021                                    *
* You will have to update your local env                        *
* instructions will be provided by `@cms-devops-engineers`      *
* in `\#cms-team` Slack                                         *
******************************ATTN*******************************
"
