#!/bin/bash

echo -e "
*******************ATTN*******************
* master branch will be renamed to main! *
* This will happen 11/3/2021             *
* You will have to update your local env *
* instructions will be provided          *   
*******************ATTN*******************
"
