#!/usr/bin/env bash

# Check a specified branch name against a list of allowed patterns.
function check_branch_name() {
  case $1 in 
    VAGOV-TEAM-[0-9]* | VACMS-[0-9]* | dependabot/* | revert-*) return 0;;
    *) return 1;;
  esac
}

# Indicate an error with the branch name.
function branch_name_error() {
  cat <<-EOF >&2
    Aborting commit. Your branch name must be prefixed with one of the following:
      - a VAGOV-TEAM-* or VACMS-* Github issue number format, 
        e.g. VAGOV-TEAM-123-issue-name or VACMS-123-issue-name. 
      - dependabot/* (for work on Dependabot PRs)
      - revert-* (for work on GitHub-initiated revert PRs)

    Use e.g. \`git branch --move <VACMS-0000-new-name>\` to rename.
EOF
  exit 1
}

branch_name=$(git rev-parse --abbrev-ref HEAD)
check_branch_name "${branch_name}" || branch_name_error

# If ddev is running, run the lints there.
if [ -x "$(command -v ddev)" ] && docker ps | grep ddev > /dev/null; then
  ddev pre-commit
else
  echo 'ddev is not running, falling back to local composer usage. Run `ddev start` to use ddev composer (recommended).'
  # Run PHP Codesniffer as pre-commit check.
  composer va:test:php_codesniffer
fi
