#!/usr/bin/env bash

branch_name=$(git rev-parse --abbrev-ref HEAD)
error_msg="Aborting commit. Your branch must start with a VAGOV-TEAM-* or VACMS-* Github issue number format, e.g. 'VAGOV-TEAM-123-issue-name or VACMS-123-issue-name. Use \`git branch --move <VACMS-0000-new-name>\` to rename."
# Regular expression to validate that the branch name starts with Jira story ID, e.g. VAGOV-000 or VACMS-000.
no_match_vagov=1; [[ $branch_name =~ VAGOV-TEAM-[0-9]+ ]] && no_match_vagov=0
no_match_vacms=1; [[ $branch_name =~ VACMS-[0-9]+ ]] && no_match_vacms=0

if [ $no_match_vagov == 1 ] && [ $no_match_vacms == 1 ]; then
    echo "${error_msg}" >&2
    exit 1
fi

# Run PHP Codesniffer as pre-commit check.
composer va:test:cs

# Run stylelint as pre-commit check if lando is available.
if [ -x "$(command -v lando)" ]; then
  lando composer va:test:lint-css-all
fi

# Run PHPStan, but only on staged files in certain directories.
git diff --diff-filter=d --cached --name-only -z -- \
  ':(exclude)docroot/core' \
  ':(exclude)docroot/sites/default' \
  ':(exclude)docroot/modules/contrib' \
  ':(exclude)docroot/vendor' \
  ':(exclude)drush' \
  ':(exclude)node_modules' \
  ':(exclude)*Test.php' \
  ':(exclude)*/tests/*' \
  '*.php' \
  '*.inc' \
  '*.module' \
  | xargs -0 -I % sh -c 'export my_file="$0"; ./docroot/vendor/bin/phpstan analyze "${my_file}" -n -l 2 --memory-limit=4000M --error-format=raw --no-progress -c phpstan.neon;' "%";
phpstan_exit=$?;
if [ ${phpstan_exit} -eq 0 ]; then
  echo -e "PHPStan failed!" 1>&2;
  exit ${phpstan_exit};
fi
