field.field_settings.entity_field_fetch:
  type: mapping
  label: 'Entity Field Fetch settings'
  mapping:
    target_type:
      type: string
      label: 'Entity type (node, term, paragraph...).'
    target_uuid:
      type: string
      label: 'Entity id (nid, or tid) where the field data lives.'
    target_field:
        type: string
        label: 'Machine name of the field value to fetch. (required for non paragraphs)'
