va_gov_notifications.no_active_users_recipient.*:
  type: config_entity
  label: 'No active users ad hoc recipient'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    status:
      type: boolean
      label: 'Enabled'
    email:
      type: string
      label: 'Email'
    notes:
      type: text
      label: 'Notes'
    products:
      type: sequence
      label: 'Product term IDs'
      sequence:
        type: string
        label: 'Product term ID'
