<?php

/**
 * @file
 * Contains va_gov_workflow.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function va_gov_workflow_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the va_gov_workflow module.
    case 'help.page.va_gov_workflow':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides customizations for publishing workflow.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Adds Validation to check for presence of revision log message.
 *
 * @param array $form
 *   The exposed widget form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function _va_gov_workflow_validate_required_revision_message(array $form, FormStateInterface &$form_state) {
  // Add revision log validation.
  if ($form_state->isValueEmpty(['revision_log', '0', 'value'])) {
    $form_state->setErrorByName('revision_log][0][value', t('Revision log message is required'));
  }
}
