<?php

/**
 * @file
 * Contains va_gov_migrate.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_entity_presave().
 */
function va_gov_migrate_entity_presave(EntityInterface $entity) {
  _va_gov_migrate_process_va_form($entity);
}

/**
 * Process VA Form.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   Entity.
 */
function _va_gov_migrate_process_va_form(EntityInterface $entity) {
  if ($entity->bundle() !== 'va_form') {
    return;
  }
  // Grab any values set in the migration.
  $migrate = (!empty($entity->migrate)) ? $entity->migrate : [];
  if (!empty($migrate['flags']['deleted'])) {
    // This should be set to unpublished because the migration is intentionally,
    // not overriding status.
    $entity->setPublished(FALSE);
    $entity->set('moderation_state', 'archived');
    $entity->set('revision_log', 'Archived because it was marked as deleted in the Forms DB.');
  }
}

/**
 * Implements hook_help().
 */
function va_gov_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the va_gov_migrate module.
    case 'help.page.va_gov_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrate content from va.gov') . '</p>';
      return $output;

    default:
  }
}
