# Update PHP-FPM pool configuration
RUN sed -i 's/pm.max_children = .*/pm.max_children = 10/' /etc/php/*/fpm/pool.d/www.conf && \
    sed -i 's/pm.start_servers = .*/pm.start_servers = 2/' /etc/php/*/fpm/pool.d/www.conf && \
    sed -i 's/pm.min_spare_servers = .*/pm.min_spare_servers = 2/' /etc/php/*/fpm/pool.d/www.conf && \
    sed -i 's/pm.max_spare_servers = .*/pm.max_spare_servers = 10/' /etc/php/*/fpm/pool.d/www.conf
