<?php

/**
 * @file
 * Adds support for returning static assets from the same URL.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function va_gov_preview_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.va_gov_preview':
      $output = '';
      $output .= '<h3>' . t('VA.gov Content Preview') . '</h3>';
      $output .= '<p>' . t('This module provides content previewing.') . '</p>';
      return $output;
  }
}

/**
 * Alter the result of \Drupal\next\Plugin\SitePreviewerInterface::render.
 *
 * This hook is called after the preview has been assembled.
 *
 * @param array &$preview
 *   The preview renderable array from the site_previewer.
 * @param array $context
 *   Context in which the entity is previewed with the following keys:
 *   - 'plugin': the site_previewer plugin.
 *   - 'entity': the entity in preview.
 *   - 'sites': the sites for this entity.
 *   - 'original_build': the original un-altered build.
 *
 * @ingroup next_api
 */
function va_gov_preview_next_site_preview_alter(array &$preview, array $context) {
  // Prevent drupal/next overwriting the existing node view content section.
  $preview['content'] = $context['original_build'][0]['content'];
  unset($preview[0]);
}
