expirable_content.expirable_content_type.*:
  type: config_entity
  label: 'Expirable Content type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
