name: CMS Team Engineering Pre-Refinement 
description: Create a ticket to document engineering pre-refinement.
title: "[CMS Team]: Engineering Pre-Refinement "
labels:
  - "CMS Team"
  - "DevOps"
  - "Drupal Engineering"
  - "Quality Assurance"
projects:
  - "department-of-veterans-affairs/1043"
  - "department-of-veterans-affairs/1044"
assignees:
  - ariperez
  - edmund-dunn
  - ndouglas
  - olivereri
  - teeshe
  - tonytaylor
body:
  - type: markdown
    attributes:
      value: |
        In preparation for this sprint's backlog refinement, please review the tickets listed below, using the following steps:

        **Review the Issue**: Begin by reading the ticket thoroughly. Understand the requirements, goals, and any associated challenges.
        If something is unclear, please comment in the ticket thread or start a thread on Slack.

        Problems with the ticket as written may include:
        - _Clarity_: If it just needs to be worded better, or provide more detail.
        - _Approach_: If you have questions or suggestions about the approach as written, or alternative approaches.
        - _Dependencies_: If there are potential blocking tickets or situations that might prevent or delay completion.
        - _Complexity_: If this ticket requires a substantial amount of knowledge and experience with the platform just to be able to 
        address this ticket comfortably.
        - _Risks_: If there are any risks associated with the ticket. This could be in terms of technical challenges, external 
        dependencies, or any other potential roadblocks.
        - _Wait-Time vs. Work Time_: If this ticket involves a substantial amount of wait time, e.g. it will involve interactions with
        other teams before the work can be completed, take that into consideration.

        **Self-assessment**: Determine whether you have all the knowledge necessary to work on this ticket independently. If not, comment
        in the ticket what additional information or clarifications you might need, or start a thread on Slack.

        **Estimation**: Based on your understanding, provide an estimate of the effort required to complete the issue. If an issue is not
        fully refined, with an estimate, I will not bring it in to refinement.
  
  - type: textarea
    attributes:
      label: Issues
      description: |
        Throw issues in here.
