name: "CMS Request"
description: Use this template to begin engaging with the CMS Team.
title: "CMS Request for [Team Name, Product Name, Feature Name]"
labels: CMS Team, Needs Analysis, Collabor
assignees:
  - gracekretschmer-metrostar

body:
  - type: markdown
    attributes:
      value: Have questions about this form? Read our CMS Request guidance or reach out directly to the CMS Team in the cms-support Slack channel.
  - type: input
    id: problem-outline
    attributes:
      label: Please describe what problem this product or feature solves
    validations:
      required: true
  - type: dropdown
    id: net-new
    attributes:
      label: Is this a net-new feature?
      description: Net-new in product development refers to the creation of a completely new feature that has not been previously implemented.
      multiple: false
      options:
        - "yes"
        - "no"
    validations:
      required: true
  - type: input
    id: editor-changes
    attributes:
      label: Will VA editors require assistance in comprehending how to utilize and/or navigate this change?
      description: 
    validations:
      required: true
  - type: input
    id: content-types
    attributes:
      label: What are the content types your team will be changing and/or creating for this work?
      description:
    validations:
      required: true
  - type: input
    id: user-flow
    attributes:
      label: Please add a link to your editor-focused user flow diagrams or wireframes.
      description: If you haven't created one yet, please forward it once it's ready for review. 
    validations:
      required: false
  - type: input
    id: content-model-changes
    attributes:
      label: Please add a link to your CMS Drupal wireframes annotating field changes.
      description: If you haven't created one yet, please forward it once it's ready for review. 
    validations:
      required: false
  - type: input
    id: optional-research
    attributes:
      label: Please add a link to your product and user research for this initiative.
      description: This is optional. If you have your research available, we would like to review it but it is not required. 
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Please provide any extra information or relevant context that may be important for your request.
  - type: checkboxes
    id: terms-agreement
    attributes:
      label:  acknowledge that I must submit this form and notify the cms-team in the cms-support Slack channel with a link to the GitHub ticket created.
      options:
        - label: I agree.
          required: true
