name: "CMS Collaboration Cycle Request"
description: Use this template to begin engaging with the CMS Collaboration Cycle.
title: "CMS Collaboration Cycle for [Team Name, Product Name, Feature Name]"
labels: CMS Team, Needs Analysis, CMS-Collab-Cycle, Epic

body:
  - type: markdown
    attributes:
      value: |
        Before engaging with the CMS team on the Collaboration Cycle, please fill out the form below to help the CMS Team determine what level of support and which touchpoints are needed for your work. Have questions about this form? Read our [Kickoff Request documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/collaboration-cycle/kickoff.md) in Github or reach out to the CMS Team in the cms-support Slack channel.
  - type: input
    id: product-outline
    attributes:
      label: Please add a link to your product outline.
      description: If you have not already made one, you can use this [product outline template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md).
    validations:
      required: true
  - type: input
    id: problem-outline
    attributes:
      label: Please describe what problem this product or feature solves
    validations:
      required: true
  - type: dropdown
    id: net-new
    attributes:
      label: Is this a net-new feature?
      multiple: false
      options:
        - "yes"
        - "no"
    validations:
      required: true
  - type: input
    id: editor-changes
    attributes:
      label: Will VA editors require assistance in comprehending how to utilize and/or navigate this change?
      description: 
    validations:
      required: true
  - type: input
    id: content-types
    attributes:
      label: What are the content types your team will be changing and/or creating for this work?
      description:
    validations:
      required: true
  - type: input
    id: user-flow
    attributes:
      label: Please add a link to your user flow diagrams or wireframes.
      description: If you have not already made one, you can forward once it is ready for review. 
    validations:
      required: false
  - type: input
    id: content-model-changes
    attributes:
      label: Please add a link to your wireframes annotating field changes.
      description: If you have not already made one, you can forward once it is ready for review. 
    validations:
      required: false
  - type: input
    id: optional-research
    attributes:
      label: Please add a link to your product and user research for this initiative.
      description: This is optional. If you have your research available, we would like to review it but it is not required. 
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Please include any additional information or context that may be relevant to your request.
  - type: checkboxes
    id: terms-agreement
    attributes:
      label: I acknowledge that I must submit this form as an Epic and notify the cms-team user group in the cms-support Slack channel with a link to the Epic that is created.
      options:
        - label: I agree.
          required: true
