blank_issues_enabled: false

cms-support:
- name: CMS support request
- about: Request training or support from a member of the CMS training team.
- title: Support for __task__
- labels: cms-support
- assignees: @howardbrande

cms-discovery:
- name: CMS discovery request
- about: Request a CMS discovery meeting.
- title: CMS discovery request: <insert product/initiative/epic name>.
- labels: cms-discovery
- assignees: @kevwalsh

cms-bug:
- name: CMS bug report.
- about: Report a bug.
- title: <description of bug.>
- labels: cms-bug
- assignees: @steveSJW 

//@todo fi

cms-access:
- name: Request CMS access
- about: Includes instructions for requesting access within the CMS itself.
- title: Requesting CMS access for <insert name>.
- labels: cms-access
- assignees: @howardbrande

cms-feature:
- name: User story or feature
- about: Request or identify a new user story or feature.
- title: <insert summary of user story or feature>
- labels: cms-feature
- assignees: @kevwalsh

cms-task:
- name: Task
- about: A standalone task for the CMS team.
- title: <insert summary of task>
- labels: cms-task
- assignees: @kevwalsh

cms-epic:
- name: Epic
- about: A collection of user stories and tasks.
- title: <insert summary of epic>
- labels: cms-epic
- assignees: @kevwalsh

cms-devops:
- name: DevOps task
- about:
- title: <insert summary of task>
- labels: devops
- assignees: @elijahlynn


# cms-FOO:
# - name:
# - about:
# - title:
# - labels:
# - assignees: @kevwalsh
