
name: "Taxonomy - Add Term"
description: "Use this template when adding terms to the Service or Benefit taxonomy."
title: "[ADD] (Term name) to (taxonomy name)"
labels: Content, sitewide

body:

- type: dropdown
  id: which-taxonomy
  attributes:
    label:  Which Taxonomy is this term for?
    multiple: false
    options:
      - VA Benefits taxonomy
      - VA services taxonomy
      - Other
  validations:
    required: true
- type: input
  id: term-name
  attributes:
    label: Proposed term name/label
    description: e.g. Veterans Pension
  validations:
    required: true
- type: input
  id: machine-name
  attributes:
    label: Proposed machine name/ API ID
    description: va_service_veterans_pension
  validations:
    required: false 
- type: dropdown
  id: overlap
  attributes:
    label: Does this overlap with any existing term in the taxonomy?
    multiple: false
    options:
      - 'Yes'
      - 'No'
  validations:
    required: true
- type: textarea
  id: rationale
  attributes:
    label: Rationale for adding this term
    description: Write a short explanation of why this term is needed. Include links to any relevant issues, research findings, etc.
  validations:
    required: true
- type: dropdown
  id: products
  attributes:
    label: Which products will this term impact?
    multiple: true
    options:
      - VAMCs
      - Vet Centers
      - VBA Regional Office
      - Benefit hubs
      - Facility Locator
      - Lighthouse VA Facilities API
      - Other
  validations:
      required: false 
- type: dropdown
  id: stakeholders
  attributes:
    label: Have stakeholders from impacted products been consulted?
    multiple: false
    options:
        - 'Yes'
        - 'No'
  validations:
    required: true  
- type: dropdown
  id: subfields
  attributes:
    label: Have you drafted content for all the relevant subfields?
    multiple: false
    options:
      - 'Yes'
      - 'No'
  validations:
    required: true
- type: textarea
  id: acceptance-critera
  attributes:
    label: Tasks
    description: Customize the Tasks or use the default
    value: |
      **Content Review and Entry**
      - [ ] Term is reviewed by relevant taxonomy governance body
      - [ ] Term is either approved for addition, or denied with an explanation
      - [ ] If approved, a Drupal admin from Product team may add the term to the taxonomy and save as Draft
      - [ ] Content for subfields is updated in Drupal by Product team
      - [ ] (List any other necessary review and approval steps here)

      **Technical Coordination**
      - [ ] Work with Lighthouse to update the Facilities API to accept new value
        - This step can begin as soon as the API ID has been finalized and saved as Draft in Drupal 
      
      **Launch & Change Management**
      - [ ] Once Content Review and Technical Coordination are complete, term can be published in Drupal
      - [ ] Updates to KB articles and other editor training materials as needed
        - [ ] If a Vet Centers service: update https://prod.cms.va.gov/help/vet-centers/how-to-edit-a-vet-center-service
      - [ ] Announcement to editors     
  validations:
    required: true

