
name: "Taxonomy - Update Term"
description: "Use this template when updating an existing terms in the Service or Benefit taxonomy."
title: "[UPDATE] (Term name) in (taxonomy name)"
labels: Content, Content governance

body:

- type: dropdown
  id: which-taxonomy
  attributes:
    label:  Which Taxonomy is this term for?
    multiple: false
    options:
      - VA Benefits taxonomy
      - VA services taxonomy
      - Other
  validations:
    required: true
- type: input
  id: term-link
  attributes:
    label: Link to existing term
    description: e.g. https://prod.cms.va.gov/health-care/medical-records
  validations:
    required: true
- type: textarea
  id: rationale
  attributes:
    label: Rationale for updating this term
    description: Write a short explanation of why this term needs to be updated. Include links to any relevant issues, research findings, etc.
  validations:
    required: true 
- type: dropdown
  id: products
  attributes:
    label: Which products will this term impact?
    multiple: true
    options:
      - VAMCs
      - Vet Centers
      - VBA Regional Office
      - Benefit hubs
      - Other
  validations:
      required: false 
- type: dropdown
  id: stakeholders
  attributes:
    label: Have stakeholders from impacted products been consulted?
    multiple: false
    options:
        - 'Yes'
        - 'No'
  validations:
    required: true  
- type: dropdown
  id: subfields
  attributes:
    label: Have you drafted content for all the relevant subfields?
    multiple: false
    options:
      - 'Yes'
      - 'No'
  validations:
    required: true   
- type: textarea
  id: acceptance-critera
  attributes:
    label: Acceptance Criteria
    description: Customize the Acceptance Critera or use the default
    value: |
      - [ ] Content for subfields is drafted in Drupal by Product team
      - [ ] Content is reviewed by relevant taxonomy governance body
      - [ ] Content is reviewed by relevant stakeholders
      - [ ] (List any necessary review and approval steps here)
      - [ ] Term is published
  validations:
    required: true
