/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  Drupal.behaviors.vaGovFixConstraintJumpLink = {
    attach: function attach() {
      var jumpLinkCorrect = function jumpLinkCorrect() {
        var jumpLink = document.querySelector(".region-highlighted .messages--error ul.item-list__comma-list li a") ? document.querySelector(".region-highlighted .messages--error ul.item-list__comma-list li a") : null;
        if (jumpLink && jumpLink.innerText === "Paths") {
          jumpLink.setAttribute("href", "#field-target-paths-values");
        }
      };
      window.addEventListener("load", jumpLinkCorrect);
    }
  };
})(Drupal);