/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(function ($, Drupal) {
  function refreshStatusBlock(url) {
    $.get(url, function (data) {
      $(".content-release-status-block").html(data);
    });
  }
  Drupal.behaviors.contentRelease = Drupal.behaviors.contentRelease || {};
  Drupal.behaviors.contentRelease.statusBlock = {
    attach: function attach(context, settings) {
      $(window, context).once("contentRelease.statusBlock").on("load", function () {
        window.setInterval(function () {
          refreshStatusBlock(settings.contentRelease.statusBlock.blockRefreshPath);
        }, 10000);
      });
    }
  };
})(jQuery, window.Drupal);