# Default state for all rules
default: true

# Disable line length rule.
MD013: false

# Path to configuration file to extend
extends: null

MD025:
  # Ignore the front matter title for purposes of heading hierarchy.
  front_matter_title: ""
