<?php

/**
 * @file
 * Contains va_gov_manila.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function va_gov_manila_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  $list_item_bundles = [
    'event',
    'news_story',
    'press_release',
  ];
  if (($entity_type->id() === 'node')
  && (in_array($bundle, $list_item_bundles))
  && (isset($fields['field_listing']))
  && (isset($fields['field_administration']))) {
    // Limit the listing selection based on section.
    $fields['field_listing']->addConstraint('ManilaSectionListParity');
  }
}
