FROM devwithlando/php:7.2-apache

RUN apt-get update -y \
  && docker-php-ext-install pcntl

RUN mkdir /var/www/.drush
RUN mkdir /var/www/.drupal
COPY config/services/config/php/php.ini /usr/local/etc/php/conf.d/xxx-lando-default.ini
COPY config/services/config/php/httpd-ssl.conf /etc/apache2/sites-enabled/000-default.conf
COPY config/services/config/drupal8/php.ini /usr/local/etc/php/conf.d/zzz-lando-my-custom-ini-file-called-php.ini
COPY config/engine/scripts/lando-entrypoint-app.sh /lando-entrypoint.sh
COPY config /lando
COPY config/engine/scripts/user-perms.sh /helpers/user-perms.sh
COPY config/engine/scripts/add-cert.sh /scripts/add-cert.sh
COPY config/engine/scripts/load-keys.sh /scripts/load-keys.sh
COPY config/services/helpers/sql-import.sh /helpers/sql-import.sh
COPY config/services/helpers/sql-export.sh /helpers/sql-export.sh
COPY config/engine/scripts/wait-for-it.sh /usr/bin/wait-for-it.sh
COPY . /app

# Custom vagovcms settings
RUN apt-get update -y
RUN apt-get install python-pip -y
RUN pip install j2cli
RUN mkdir /templates
COPY templates/* /templates/
RUN cd /app && composer install
