/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal, drupalSettings) {
  Drupal.behaviors.parentMenuSelector = {
    attach: function attach(context) {
      var currentUserRoles = drupalSettings.vagov_menu_access.current_user_roles;
      var adminRoles = ["content_admin", "administrator"];
      var adminTest = adminRoles.some(function (role) {
        return currentUserRoles.includes(role);
      });
      var menuEnableCheckbox = document.getElementById("edit-menu-enable");

      function menuSelectHandler() {
        if (document.querySelector(".menu-parent-select").classList.contains("no-available-menu-targets")) {
          document.getElementById("edit-menu").style.display = "none";
        }

        var parentOptions = context.querySelectorAll("#edit-menu-menu-parent option");

        if (document.getElementById("edit-menu-title").hasAttribute("disabled") && menuEnableCheckbox !== null) {
          menuEnableCheckbox.disabled = true;
        }

        parentOptions.forEach(function (opt) {
          if (opt && opt.text.includes(" | Disabled")) {
            opt.setAttribute("disabled", "");

            opt.innerHTML = opt.text.replace(/ \| Disabled/gi, "").replace(/\(disabled\)/gi, "").replace(/no-link/gi, "");
          }
        });
      }

      if (!adminTest) {
        window.addEventListener("load", menuSelectHandler);
      }
    }
  };
})(Drupal, drupalSettings);