/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal, drupalSettings) {
  Drupal.behaviors.parentMenuSelector = {
    attach: function attach(context) {
      var currentUserRoles = drupalSettings.vagovmenuaccess.currentuserroles;
      var adminRoles = ["content_admin", "administrator"];
      var adminTest = adminRoles.some(function (role) {
        return currentUserRoles.includes(role);
      });

      function menuSelectHandler() {
        var approvedRoles = drupalSettings.vagovmenuaccess.allowedroles;
        var approvedMenusObj = drupalSettings.vagovmenuaccess.allowedmenus;
        var approvedMenus = Object.entries(approvedMenusObj);

        var parentOptions = context.querySelectorAll("#edit-menu-menu-parent option");
        var menuTest = void 0;
        var roleTest = void 0;
        parentOptions.forEach(function (opt) {
          roleTest = approvedRoles.some(function (role) {
            return currentUserRoles.includes(role);
          });

          menuTest = approvedMenus.some(function (menu) {
            return opt.value.includes(menu[0]);
          });

          if (!roleTest || opt && opt.value && !menuTest) {
            opt.setAttribute("disabled", "");
          }
        });
      }

      if (!adminTest) {
        document.addEventListener("readystatechange", menuSelectHandler);
      }
    }
  };
})(Drupal, drupalSettings);