/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.OnThisPage = {
    attach: function attach() {
      console.log('ethan is here');
    }
  };
})(jQuery, window.Drupal);