/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(function ($, once, Drupal, drupalSettings) {
  var trackMediaEvent = function trackMediaEvent(event) {
    if (typeof gtag === 'function') {
      gtag('event', event.type, {
        event_category: 'Media',
        event_label: event.target.src || event.target.href
      });
    }
  };
  var trackUploadFileSelection = function trackUploadFileSelection(fileName) {
    if (typeof gtag === 'function') {
      gtag('event', 'image_upload', {
        event_category: 'Media',
        event_label: fileName || 'file_selected',
        upload_action: 'file_selected'
      });
    }
  };
  var trackUploadButtonClick = function trackUploadButtonClick(label) {
    if (typeof gtag === 'function') {
      gtag('event', 'image_upload', {
        event_category: 'Media',
        event_label: label || 'upload_button',
        upload_action: 'button_click'
      });
    }
  };
  Drupal.behaviors.vaGovMedia = {
    attach: function attach(context) {
      try {
        console.debug('vaGovMedia behavior attach', context);
      } catch (e) {}
      var fileInputs = once('va-gov-media-upload-file', 'input[type="file"]', context || document);
      try {
        console.debug('vaGovMedia: file inputs found', fileInputs && fileInputs.length ? fileInputs.length : fileInputs);
      } catch (e) {}
      fileInputs.forEach(function (input) {
        input.addEventListener('change', function (e) {
          var f = e.target.files && e.target.files[0] ? e.target.files[0].name : '';
          try {
            console.debug('vaGovMedia: file input change', f);
          } catch (err) {}
          trackUploadFileSelection(f);
        });
      });
      var buttonSelector = 'input[accept="image/*"]';
      var uploadButtons = once('va-gov-media-upload-btn', buttonSelector, context || document);
      try {
        console.debug('vaGovMedia: upload buttons found', uploadButtons && uploadButtons.length ? uploadButtons.length : uploadButtons);
      } catch (e) {}
      uploadButtons.forEach(function (btn) {
        btn.addEventListener('click', function (e) {
          var label = btn.getAttribute('aria-label') || btn.textContent.trim();
          try {
            console.debug('vaGovMedia: upload button clicked', label);
          } catch (err) {}
          trackUploadButtonClick(label);
        });
      });
      if (!uploadButtons || uploadButtons.length === 0) {
        try {
          console.debug('vaGovMedia: no upload buttons found; adding delegated listener for', buttonSelector);
        } catch (e) {}
        document.addEventListener('click', function delegatedUploadClick(e) {
          var target = e.target;
          var match = target.closest ? target.closest(buttonSelector) : null;
          if (match) {
            var label = match.getAttribute('aria-label') || match.textContent.trim();
            try {
              console.debug('vaGovMedia: delegated upload click', label);
            } catch (err) {}
            trackUploadButtonClick(label);
          }
        });
      }
    }
  };
})(jQuery, once, Drupal, drupalSettings);