<?php

/**
 * @file
 * Contains va_gov_api.module.
 */

/**
 * Alter the result of \Drupal\next\Plugin\SitePreviewerInterface::render.
 *
 * This hook is called after the preview has been assembled.
 *
 * @param array &$preview
 *   The preview renderable array from the site_previewer.
 * @param array $context
 *   Context in which the entity is previewed with the following keys:
 *   - 'plugin': the site_previewer plugin.
 *   - 'entity': the entity in preview.
 *   - 'sites': the sites for this entity.
 *   - 'original_build': the original un-altered build.
 *
 * @ingroup next_api
 */
function va_gov_api_next_site_preview_alter(array &$preview, array $context) {
  // Don't let next overwrite the existing node view page.
  $preview['content'] = $context['original_build'][0]['content'];

  // See va_gov_backend_preprocess_page() for existing preview button logic.
}
