<?php

/**
 * @file
 * Hooks used by the va_gov_api module.
 */

/**
 * Implements hook_page_attachments().
 *
 * Limit the UI options for OpenAPI documentation.
 */
function va_gov_api_page_attachments(array &$attachments): void {
  $current_path = \Drupal::service('path.current')->getPath();
  if ($current_path == '/admin/config/services/openapi') {
    $attachments['#attached']['library'][] = 'va_gov_api/json_schemas_table_filter';
  }
}
