_core:
  default_config_hash: oDGEkhP0h5rXXqlDplxeBDre0goLigOJupHKMDMwcqM
login_menu_item_title: ''
logout_menu_item_title: ''
login_redirect_url: ''
logout_redirect_url: ''
error_redirect_url: ''
error_throw: false
local_login_saml_error: true
logout_different_user: false
drupal_login_roles:
  authenticated: authenticated
  content_api_consumer: content_api_consumer
  content_editor: content_editor
  content_reviewer: content_reviewer
  content_publisher: content_publisher
  content_admin: content_admin
  redirect_administrator: redirect_administrator
  admnistrator_users: admnistrator_users
  administrator: administrator
  content_creator_benefits_hubs: '0'
  content_creator_resources_and_support: '0'
  office_content_creator: '0'
  vamc_content_creator: '0'
  content_creator_vet_center: '0'
  homepage_manager: '0'
  translation_manager: '0'
sp_entity_id: 'https://staging.cms.va.gov/saml/metadata'
sp_name_id_format: 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified'
sp_x509_certificate: MIIDozCCAoqgAwIBAgIBADANBgkqhkiG9w0BAQ0FADBrMQswCQYDVQQGEwJ1czEOMAwGA1UECAwFSWRhaG8xFTATBgNVBAoMDGN3ZWFnYW5zLm5ldDEVMBMGA1UEAwwMY3dlYWdhbnMubmV0MR4wHAYJKoZIhvcNAQkBFg9tZUBjd2VhZ2Fucy5uZXQwHhcNMTUwNjIzMjAwMjMyWhcNMjUwNjIwMjAwMjMyWjBrMQswCQYDVQQGEwJ1czEOMAwGA1UECAwFSWRhaG8xFTATBgNVBAoMDGN3ZWFnYW5zLm5ldDEVMBMGA1UEAwwMY3dlYWdhbnMubmV0MR4wHAYJKoZIhvcNAQkBFg9tZUBjd2VhZ2Fucy5uZXQwggEjMA0GCSqGSIb3DQEBAQUAA4IBEAAwggELAoIBAgDDZOeQF9Cp5k0WzNBye9S/3FgKxTZjcAPBFLtMMAhcx9+kLYMwS5J5h1OUKQcaoxmz/MiVKnrnozStdOKYIeS0C+8DmjRPjKEva77RYEy/Zu4l2Y+Nijt9/OMrO2JwuchHI9Xx+rqifDCR9rJ4vwbu/6/NhTVggSgsDsxlgGtLWC1zoUmwtcBe30t63P1eDrNAEg5EkM3y6OCsx6HaK7nAJmGaF6of/60UmEXB6qBVgZlU/qUmrVX89EdGvPrKWvYJcX3xAcIQh/on/1e/XmGMRYnBB6E0qyx6sL0ZmHzwH5jIUR5S1xwqWhSAjlOUHLSg2tYfHx0dn3UV2koY9QsKEQIDAQABo1AwTjAdBgNVHQ4EFgQUTJG5GAzq0olNiSfg7c/zjaBHnwcwHwYDVR0jBBgwFoAUTJG5GAzq0olNiSfg7c/zjaBHnwcwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQ0FAAOCAQIAsaxgtTmqQLbNETa7pLD0q0qCU7awxUUfwM73CwW+uIoZXeTz4YP6qaQ9T8kbBjyQKK9jmvTCHHm7y7U7a6NTj3DHuGpjo6mOXNMeh259iCSOfxpm2hMnUsLuQk3dM1+POJWSRQ8LFUcx9WT7siqvKfKq8cTjul7DMRR3MWOAgcd6N+ru3UYsuU81M0Gar417va+GkdMhoRBGT/K6jz9dkvOdQWmIlitYGvkQ6o7VGM5wB9J9wZ/A5FDJ0/IxGXJDD8aFtst8RTBwf8Cgptbmmycu9jqrby4bDLQ5ygviBZ7ZvXt4c9pOPWtXxvloilUNM992EVFyiJTTg9yniXcZSsU=
sp_new_certificate: ''
sp_private_key: MIIEwQIBADANBgkqhkiG9w0BAQEFAASCBKswggSnAgEAAoIBAgDDZOeQF9Cp5k0WzNBye9S/3FgKxTZjcAPBFLtMMAhcx9+kLYMwS5J5h1OUKQcaoxmz/MiVKnrnozStdOKYIeS0C+8DmjRPjKEva77RYEy/Zu4l2Y+Nijt9/OMrO2JwuchHI9Xx+rqifDCR9rJ4vwbu/6/NhTVggSgsDsxlgGtLWC1zoUmwtcBe30t63P1eDrNAEg5EkM3y6OCsx6HaK7nAJmGaF6of/60UmEXB6qBVgZlU/qUmrVX89EdGvPrKWvYJcX3xAcIQh/on/1e/XmGMRYnBB6E0qyx6sL0ZmHzwH5jIUR5S1xwqWhSAjlOUHLSg2tYfHx0dn3UV2koY9QsKEQIDAQABAoIBAUs9S728rej+eajR7WJoNKA8pNpg3nSj6Y4sAYNw64dun7uEmwO51gleBt0Cf23OaFNaf5KQ7QrNWbeBTs/uHTcHcV4dvw7yxA6SmsPdJTB+3i1M/W4vUIFPI9q930YxA+IA9p1bQwrWb42FRWwhgvX9FyE4rjkfAu0UNbjQHoDAxNFHHW2OZm9DFtZE8Y3qFFLXjnwl2acFncexDbY0A9vVR+ldpTruz7LQXRmAhozXmVnRtzMlDWDB0hjUQJYIAuue6tTHuD6VcxGLKYUgfB4AZ8IkvD2cbky38omll3KvaPbtOJFGNsBaqt0PVrZv//iZQHgIZe2roKNGBpUNA/7BAoGBD0H/eeG8KoFjLyqLLlBDndHPb3aURJGqf/rFuooK29NBn5n30cftFv7mXc+RA9/SBbIrX5+0p6Nez4SuJLYfVHBzDF9YOVzQbDUWZZWIUtR0yBSl2WAFEET7jyofzXTKOCo2eFrnWj5a2Q0xEFj11f7q83pbdQ8HvbUdi+roaRCtAoGBDM5hrDc4CI8yR6La9fAtA4bkQ/SxiDwfh/Xnjg0eSiVIs5GeGCAJEIeNoZE7n9BQHhH5m0HyjHMnzMfLyexhW6/xHAktEvcEWZMBBIBTbXsGn/f4yKiyfLCsdoLtQIBBQTpYAXwbqVjE+L6xgK/noFdDV17XZcYbPk6xr+f6Hnd1AoGBCQi2z9/Mng5GP+MczatQnd1gyUqYt5DYNzawZKbfjxEixfFQPrH1u6vpkpoX7wdTP3QjIldZi/i7ZnvU8H+1RTXfqO+7ORuvfKJiRHupYAHTs7QmDvM/jEaL/FSgx/Hi2iaEYfbRDSnmeKXK6zcBOFfbnZZRGJpxpu3aNMI+IhdxAoGBC2RplWeGDG8+3mVs/k6L7NBKLn32lOhPcIb8V+0pnfIvC7el+XY+OhssjqeBcDlDnIyHDWwMVo92v4CZtOb48TTCfBtZor5mez0AMb3q+cDw8swI4JDaP3x33/G3F6NA6cL6WU/L18nlaBdUFtPlbUlT2dzAJ4Sl5bbh8UefxQylAoGBAKP0QllPVH3cAKcplu/vTm3Brw6cejhwUX21qBspHJDQcjbqQMqI4xdcY7oYwBGazgPKnBOgiRqSg4018dcJySL5tHneGuTXHVfp+4FznlOQKxRg7I6e/KUOzRSsLy49KlGs9OmuACe0MOTboDIn00mzUnxdmk4qsq34KaqJ4w5G
metadata_valid_secs: 60
metadata_cache_http: false
idp_entity_id: VA_SSOi_IDP
idp_single_sign_on_service: 'https://logon.preprod.iam.va.gov/affwebservices/public/saml2sso'
idp_single_log_out_service: ''
idp_change_password_service: ''
idp_certs:
  - MIIFbjCCBFagAwIBAgIHPQAAAAAl8TANBgkqhkiG9w0BAQsFADBIMRMwEQYKCZImiZPyLGQBGRYDZ292MRIwEAYKCZImiZPyLGQBGRYCdmExHTAbBgNVBAMTFFZBLUludGVybmFsLVMyLUlDQTExMB4XDTIzMDQyNDE5NTE0NloXDTI2MDQyMzE5NTE0NlowgZExCzAJBgNVBAYTAlVTMREwDwYDVQQIEwhWaXJnaW5pYTEQMA4GA1UEBxMHQXNoYnVybjEsMCoGA1UEChMjVS5TLiBEZXBhcnRtZW50IG9mIFZldGVyYW5zIEFmZmFpcnMxDDAKBgNVBAsTA0lBTTEhMB8GA1UEAxMYbG9nb24ucHJlcHJvZC5pYW0udmEuZ292MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6PrQ8/4681Ie9Zo0NbmkW7uBdLKeCPNkz3zy5PG0UC5Bp+LhmgHtSlchOWF0VW7CBbXzSXfmTvN4joyZ3xQ/wKdR4lfudmSF7HZY0GjdEvP5X03VCDf6PWgY+44Wdq7cuWPxNyr7mhuiuyMOjtuZ/439TRHVlJgvFRiZWOG35Dy5lPR4Erd4CgvNHpRTKgtz25nuPTY4k+JXJS7fEiRLVRJxHZpnVCmQ7Dk9NU1EXuSRice4/A7gMANweP7FfBeY4b54MHePseF/mZw1aUkEHvKTnGouD2LZbFN9yVHIUyQ8S7g1kanCmwjh3qPvGrA4SCUR0dCihaQmDoh30e8DhQIDAQABo4ICETCCAg0wZQYDVR0RBF4wXIIYbG9nb24ucHJlcHJvZC5pYW0udmEuZ292ghRsb2dvbi5zcWEuaWFtLnZhLmdvdoIUbG9nb24uaW50LmlhbS52YS5nb3aCFGxvZ29uLmRldi5pYW0udmEuZ292MB0GA1UdDgQWBBTuPcXQZrik6S4mKfISFYtVFy2HiDAfBgNVHSMEGDAWgBQiWIgZKReBlp33yagYLHUqfBQsqTBHBgNVHR8EQDA+MDygOqA4hjZodHRwOi8vY3JsLnBraS52YS5nb3YvcGtpL2NybC9WQS1JbnRlcm5hbC1TMi1JQ0ExMS5jcmwweQYIKwYBBQUHAQEEbTBrMEUGCCsGAQUFBzAChjlodHRwOi8vYWlhLnBraS52YS5nb3YvcGtpL2FpYS92YS9WQS1JbnRlcm5hbC1TMi1JQ0ExMS5jZXIwIgYIKwYBBQUHMAGGFmh0dHA6Ly9vY3NwLnBraS52YS5nb3YwDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCBPAwPQYJKwYBBAGCNxUHBDAwLgYmKwYBBAGCNxUIgcjDM4H58AaBpZ8NhOCBCIXCqksGgb3hO4KrxyACAWQCATUwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMCcGCSsGAQQBgjcVCgQaMBgwCgYIKwYBBQUHAwIwCgYIKwYBBQUHAwEwDQYJKoZIhvcNAQELBQADggEBAJaCuvXMbJxxGKIdMhg6xIjlgj3Q8ibjfXrnKc86lw/cUj5rdDkesK5NUGfI83p6MQ6pxevj+OZDasnlRlk7pyGzZRB98WN3u5hjuuyDjT8OW425WcNOk41tP/cnHBzVucY65fkdQPE6zfTfHy+z3OXynAZNDG67LOfKbFl6utjdGwHE3ayOyGfBUTuKjeNPdFA77fkAj7SgmED1At+TeV1cZFoGnSi+Sv9NIs22F2sJguMauVcyx18BdqDpWVRLgW4rjrl55afVTty9jKkSVY/VAGcEXEAyUxpifbhwoEGxAfUdLnnSyHE349kKUKfny3ZB5OAZXXkTNpPBKxWxc4I==
idp_cert_encryption: ''
unique_id_attribute: VAUID
map_users: false
map_users_name: true
map_users_mail: true
map_users_roles:
  content_creator_benefits_hubs: content_creator_benefits_hubs
  content_creator_resources_and_support: content_creator_resources_and_support
  office_content_creator: office_content_creator
  vamc_content_creator: vamc_content_creator
  content_creator_vet_center: content_creator_vet_center
  content_editor: content_editor
  content_reviewer: content_reviewer
  content_publisher: content_publisher
  content_admin: content_admin
  redirect_administrator: redirect_administrator
  admnistrator_users: admnistrator_users
  administrator: administrator
  homepage_manager: homepage_manager
  translation_manager: translation_manager
  content_api_consumer: '0'
create_users: true
sync_name: true
sync_mail: true
user_name_attribute: adUPN
user_mail_attribute: adUPN
request_set_name_id_policy: true
strict: true
security_metadata_sign: false
security_authn_requests_sign: true
security_logout_requests_sign: false
security_logout_responses_sign: false
security_nameid_encrypt: false
security_signature_algorithm: ''
security_encryption_algorithm: ''
security_messages_sign: false
security_assertions_signed: true
security_assertions_encrypt: true
security_nameid_encrypted: false
security_want_name_id: false
security_request_authn_context: false
security_lowercase_url_encoding: true
security_logout_reuse_sigs: false
security_allow_repeat_attribute_name: false
debug_display_error_details: true
debug_log_in: false
debug_log_saml_in: false
debug_log_saml_out: false
debug_phpsaml: false
use_proxy_headers: false
use_base_url: true
