<?php

/**
 * @file
 * Contains va_gov_content_types.module.
 */

use Drupal\va_gov_content_types\Entity\VaNode;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function va_gov_content_types_entity_bundle_info_alter(array &$bundles): void {
  $bundleClasses = [];
  foreach (array_keys($bundles['node']) as $machine_name) {
    $bundles['node'][$machine_name]['class'] = $bundleClasses[$machine_name] ?? VaNode::class;
  }
}
