<?php

/**
 * @file
 * Contains va_gov_user.module.
 */

use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Redirect user to section on login if they only have one section assigned.
 *
 * Implements hook_user_user_login().
 */
function va_gov_user_user_login($account) {
  $sections = \Drupal::service('va_gov_user.user_perms')->getSections($account);
  $route_name = \Drupal::routeMatch()->getRouteName();
  if (count($sections) === 1 && $route_name === 'user.login') {
    $alias_manager = \Drupal::service('path_alias.manager');
    $alias = $alias_manager->getAliasByPath('/taxonomy/term/' . key($sections));
    $response = new RedirectResponse($alias);
    // Save the session so login works.
    // Refactor the redirect code out of hook_user_login().
    // See https://www.drupal.org/node/2023537 and
    // https://www.drupal.org/node/3006306.
    $request = \Drupal::request();
    $request->getSession()->save();
    $response->prepare($request);
    // Make sure to trigger kernel events.
    \Drupal::service('kernel')->terminate($request, $response);
    $response->send();
  }
}
