<?php

/**
 * @file
 * Contains va_gov_vet_center.module.
 */

use Drupal\Core\Entity\ContentEntityForm;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function va_gov_vet_center_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the va_gov_vet_center module.
    case 'help.page.va_gov_vet_center':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom code for Vet centers') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 *
 * @todo Use for vc dashboard theme work.
 */
function va_gov_vet_center_theme() {
  return [
    'va_gov_vet_center' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_entity_presave().
 */
function va_gov_vet_center_entity_presave(EntityInterface $entity) {
  if ($entity->bundle() === 'vet_center_cap') {
    _va_gov_vet_center_create_cap_id($entity);
  }
}

/**
 * Creates unique VC Cap facility id.
 *
 * @param Drupal\Core\Entity\EntityInterface $entity
 *   The vc cap node.
 */
function _va_gov_vet_center_create_cap_id(EntityInterface $entity) {
  if (empty($entity->field_facility_locator_api_id->value)) {
    // Set our vc cap facility id field for lighthouse if field is empty.
    // Step 1: Trim suffixes: os | v | mvc
    // Step 2: query for this type of pattern ---> vc_0204CP123.
    $vc_id = '';
    if (!empty($entity->field_office->entity->field_facility_locator_api_id->value)) {
      $vc_id = $entity->field_office->entity->field_facility_locator_api_id->value;
    }
    // VC suffixes.
    $patterns = [
      '/OS(?!\S)/',
      '/V(?!\S)/',
      '/MVC(?!\S)/',
    ];
    $replacements = [
      'CAP',
      'CAP',
      'CAP',
    ];
    $vc_search_string = preg_replace($patterns, $replacements, $vc_id, 1);
    $database = \Drupal::database();
    // Grab our caps.
    $results = $database->select('node__field_facility_locator_api_id', 't')
      ->fields('t', ['field_facility_locator_api_id_value'])
      ->condition('field_facility_locator_api_id_value', "%" . $database->escapeLike($vc_search_string) . "%", 'LIKE')
      ->execute()
      ->fetchAll();
    $highest_cap = 0;
    if (!empty($results)) {
      // Stuff our cap numbers into an array.
      $facilities_array = [];
      foreach ($results as $key => $facility_value_from_db) {
        preg_match("/CAP(.*)/", $facility_value_from_db->field_facility_locator_api_id_value, $cap_id);
        $facilities_array[$key] = (integer) $cap_id[1];
      }
      sort($facilities_array);
      $highest_cap = array_pop($facilities_array);
    }
    // Add 1 to the highest cap number found.
    $index = $highest_cap + 1;
    $vcap_id = $vc_search_string . (string) $index;
    $entity->set('field_facility_locator_api_id', $vcap_id);
  }
}

/**
 * Implements hook_form_alter().
 */
function va_gov_vet_center_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id === 'node_vet_center_cap_form' || $form_id === 'node_vet_center_cap_edit_form') {
    $form['field_facility_locator_api_id']['#disabled'] = TRUE;
    // Add after_build callbacks for VC CAP node forms.
    $form['field_address']['widget']['#after_build'][] = 'va_gov_vet_center_vc_cap_address_alter_label_after_build';
    $form['field_facility_hours']['widget']['#after_build'][] = 'va_gov_vet_center_vc_cap_hours_hide_caption_after_build';
  }

  _va_gov_vet_center_office_selection_modify($form, $form_state, $form_id);

}

/**
 * Determine when and how to display office select field on node forms.
 *
 * @param array $form
 *   The form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 *
 * @return string
 *   The altered office select field.
 */
function _va_gov_vet_center_office_selection_modify(array &$form, FormStateInterface $form_state, $form_id) {
  // Only prevent user from changing on these three edit forms.
  $vc_target_bundles = [
    'node_vet_center_locations_list_edit_form',
    'node_vet_center_outstation_edit_form',
    'node_vet_center_mobile_vet_center_edit_form',
  ];
  if (in_array($form_id, $vc_target_bundles)) {
    $user_roles = \Drupal::currentUser()->getRoles();
    $admin_roles = ['content_admin', 'administrator'];
    // User isn't an admin, so logic is applied.
    if (empty(array_intersect($user_roles, $admin_roles))) {
      $form_object = $form_state->getFormObject();
      if ($form_object instanceof ContentEntityForm) {
        $form['field_administration']['#disabled'] = TRUE;
      }
    }
  }
  return $form;
}

/**
 * Change company title label in address widget on vc cap type.
 *
 * @param array $element
 *   The address widget form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 *
 * @return string
 *   The altered Address organization label.
 */
function va_gov_vet_center_vc_cap_address_alter_label_after_build(array $element, FormStateInterface $form_state) {
  $element[0]['address']['organization']['#title'] = t('Located at');
  return $element;
}

/**
 * Hide hours caption in hours widget on vc cap type.
 *
 * @param array $element
 *   The hours table widget form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 *
 * @return string
 *   The altered hours table widget.
 */
function va_gov_vet_center_vc_cap_hours_hide_caption_after_build(array $element, FormStateInterface $form_state) {
  unset($element[0]['#description']);
  unset($element[0]['caption']);
  return $element;
}
