/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(function (Drupal, once, drupalSettings) {
  Drupal.behaviors.vaGovVamcArchiveConfirm = {
    attach: function attach(context) {
      var settings = drupalSettings.va_gov_vamc && drupalSettings.va_gov_vamc.archiveConfirm;
      if (!settings || !settings.facilityCount || !settings.message) {
        return;
      }
      var forms = once("va-gov-vamc-archive-confirm", document.querySelectorAll(["form.node-health-care-local-health-service-edit-form", "form.node-regional-health-care-service-des-edit-form"].join(", ")), context);
      forms.forEach(function (form) {
        var submitBtn = form.querySelector('input.form-submit#edit-submit[value="Save"]');
        if (!submitBtn) {
          return;
        }
        var handleClick = function handleClick(e) {
          e.preventDefault();
          e.stopImmediatePropagation();
          var modal = document.getElementById("va-gov-vamc-archive-modal");
          if (!modal) {
            modal = document.createElement("dialog");
            modal.id = "va-gov-vamc-archive-modal";
            modal.setAttribute("aria-modal", "true");
            modal.setAttribute("role", "dialog");
            modal.innerHTML = "\n              <form method=\"dialog\" class=\"va-gov-vamc-archive-modal-form\">\n                <div id=\"va-gov-vamc-archive-modal-message\"></div>\n                <div class=\"va-gov-vamc-archive-modal-actions\">\n                  <button value=\"cancel\" type=\"button\" id=\"va-gov-vamc-archive-cancel\">" + Drupal.t("Cancel") + "</button>\n                  <button value=\"confirm\" type=\"submit\" id=\"va-gov-vamc-archive-confirm\">" + Drupal.t("Confirm") + "</button>\n                </div>\n              </form>";
            document.body.appendChild(modal);
          }
          modal.querySelector("#va-gov-vamc-archive-modal-message").textContent = settings.message;
          setTimeout(function () {
            var f = modal.querySelector("button");
            if (f) f.focus();
          }, 0);
          modal.querySelector("#va-gov-vamc-archive-cancel").onclick = function () {
            modal.close("cancel");
          };
          modal.querySelector("#va-gov-vamc-archive-confirm").onclick = function (evt) {
            evt.preventDefault();
            modal.close("confirm");
          };
          modal.addEventListener("close", function () {
            if (modal.returnValue === "confirm") {
              submitBtn.removeEventListener("click", handleClick);
              submitBtn.click();
            }
            setTimeout(function () {
              modal.remove();
            }, 100);
          }, {
            once: true
          });
          modal.showModal();
          return false;
        };
        submitBtn.addEventListener("click", handleClick);
      });
    }
  };
})(Drupal, window.once, window.drupalSettings);