/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(function (Drupal, once, drupalSettings) {
  Drupal.behaviors.vaGovVamcArchiveConfirm = {
    attach: function attach(context) {
      var settings = drupalSettings.va_gov_vamc && drupalSettings.va_gov_vamc.archiveConfirm;
      if (!settings || !settings.facilityCount || !settings.message) {
        return;
      }
      var forms = once("va-gov-vamc-archive-confirm", document.querySelectorAll("form.node-regional-health-care-service-des-edit-form, form.node-regional-health-care-service-des-form"), context);
      forms.forEach(function (form) {
        form.addEventListener("submit", function (e) {
          var moderationState = form.querySelector('[name^="moderation_state"]');
          if (moderationState && moderationState.value === "archived") {
            var confirmed = window.confirm(settings.message);
            if (!confirmed) {
              e.preventDefault();
              e.stopImmediatePropagation();
              return false;
            }
          }
        });
      });
    }
  };
})(Drupal, window.once, window.drupalSettings);