/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  var titleSetter = function titleSetter() {
    var title = document.getElementById("edit-title-0-value");
    title.dispatchEvent(new MouseEvent("click", { shiftKey: true }));
    var menuTitle = document.getElementById("edit-menu-title");
    menuTitle.value = title.value;

    menuTitle.setAttribute("aria-disabled", true);
    menuTitle.classList.add("disabled-title");
  };
  Drupal.behaviors.vaGovSetMenuTitle = {
    attach: function attach() {
      window.addEventListener("DOMContentLoaded", titleSetter);
    }
  };
})(Drupal);