/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }

(function ($, Drupal) {
  Drupal.behaviors.vaGovSetServiceSelects = {
    attach: function attach(context) {
      var adminRoles = ["content_admin", "administrator"];

      $(context).ajaxComplete(function () {
        var vamcSection = context.getElementById("edit-field-administration");

        var vamcSectionValue = vamcSection.options[vamcSection.selectedIndex].text;

        var admins = context.querySelector(".field--type-entity-reference.field--name-field-administration select");
        var allAdmins = context.querySelectorAll(".field--name-field-banner-alert .field--type-entity-reference.field--name-field-administration.field--widget-options-select");

        if (!adminRoles.some(function (item) {
          return drupalSettings.gtm_data.userRoles.includes(item);
        }) && allAdmins) {
          allAdmins.forEach(function (admin) {
            admin.style.display = "none";
          });
        }

        if (admins) {
          admins.selectedIndex = [].concat(_toConsumableArray(admins.options)).findIndex(function (option) {
            return option.text === vamcSectionValue;
          });
        }
      });
    }
  };
})(jQuery, Drupal);