/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  var title = document.getElementById("edit-title-0-value");
  var titleSetter = function titleSetter() {
    var menuTitle = document.getElementById("edit-menu-title");
    menuTitle.value = title.value;

    menuTitle.setAttribute("aria-disabled", true);
    menuTitle.classList.add("disabled-title");
  };
  Drupal.behaviors.vaGovSetMenuTitle = {
    attach: function attach() {
      titleSetter();
      title.addEventListener("input", titleSetter);
    }
  };
})(Drupal);