# Schema for the configuration files of the va_gov_bulk module.
# set up the actions for bulk operations for publish and unpublish on /admin/content view.
action.configuration.archive_node_action:
  type: action_configuration_default
  label: 'Archive selected content (Unpublish)'

action.configuration.publish_latest_revision_action:
  type: action_configuration_default
  label: 'Publish latest revision'
