FROM ubuntu:22.04

# Prevent interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    mysql-client \
    nfs-common \
    awscli \
    curl \
    gzip \
    tar \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace