/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.vaGovDisplayServiceDescriptions = {
    attach: function attach(context) {
      var removeItems = function removeItems() {
        return context.querySelectorAll(".health_service_text_container").forEach(function (item) {
          item.remove();
        });
      };
      var descriptionFill = function descriptionFill(ss) {
        if (ss && ss.length > 0) {
          ss.forEach(function (service) {
            service.addEventListener("change", function () {
              removeItems();
              var div = context.createElement("div");
              div.className = "health_service_text_container";

              if (drupalSettings.availableHealthServices[service.value].type) {
                var p1 = context.createElement("p");
                var s1 = context.createElement("strong");
                var typeString = drupalSettings.availableHealthServices[service.value].type;
                p1.textContent = typeString;
                s1.textContent = "Type of care: ";
                div.appendChild(p1);
                p1.prepend(s1);
              }
              if (drupalSettings.availableHealthServices[service.value].name) {
                var p2 = context.createElement("p");
                var s2 = context.createElement("strong");
                p2.textContent = drupalSettings.availableHealthServices[service.value].name;
                s2.textContent = "Patient friendly name: ";
                div.appendChild(p2);
                p2.prepend(s2);
              }
              if (drupalSettings.availableHealthServices[service.value].conditions) {
                var p3 = context.createElement("p");
                var s3 = context.createElement("strong");
                p3.textContent = drupalSettings.availableHealthServices[service.value].conditions;
                s3.textContent = "Common conditions: ";
                div.appendChild(p3);
                p3.prepend(s3);
              }
              if (drupalSettings.availableHealthServices[service.value].description) {
                var p4 = context.createElement("p");
                var s4 = context.createElement("strong");
                p4.textContent = drupalSettings.availableHealthServices[service.value].description;
                s4.textContent = "Service description: ";
                div.appendChild(p4);
                p4.prepend(s4);
              }

              service.after(div);
            });
          });
        }
      };

      $(context).ajaxComplete(function () {
        var serviceSelects = context.querySelectorAll(".field--name-field-service-name-and-descripti select");
        descriptionFill(serviceSelects);
      });
    }
  };
})(jQuery, Drupal);