/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  var adminField = document.getElementById("edit-field-administration");
  var vcFieldOptions = document.querySelectorAll("#edit-field-office option");
  var vcField = document.getElementById("edit-field-office");
  var winnower = function winnower() {
    var pathType = drupalSettings.path.currentPath.split("/")[1];

    if (typeof vcField !== "undefined" && vcField !== null && pathType === "add") {
      vcField.selectedIndex = "_none";
    }

    var adminFieldText = adminField.options[adminField.selectedIndex].text;

    var adminMatcher = adminFieldText.replace(/(^-+)/g, "");

    vcFieldOptions.forEach(function (i) {
      i.classList.remove("hidden-option");
      if (!i.text.includes(adminMatcher)) {
        i.classList.add("hidden-option");
      }
    });
  };

  Drupal.behaviors.vaGovLimitVcServiceOptions = {
    attach: function attach() {
      winnower();
      adminField.addEventListener("change", winnower);
    }
  };
})(Drupal);