/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  var servicesFieldset = document.getElementById("inline-entity-form-field_health_services-form");
  var winnower = function winnower(context) {
    var selectedValues = context.querySelectorAll("#inline-entity-form-field_health_services-form td.inline-entity-form-node-label");

    var newServiceValueSelector = context.querySelectorAll("#inline-entity-form-field_health_services-form .field--name-field-service-name-and-descripti select option");

    var selectedValuesText = new Set();
    if (newServiceValueSelector) {
      selectedValues.forEach(function (i) {
        selectedValuesText.add(i.textContent);
      });

      newServiceValueSelector.forEach(function (i) {
        i.classList.remove("hidden-option");

        if (selectedValuesText.has(i.text)) {
          i.classList.add("hidden-option");
        }
      });
    }
  };

  Drupal.behaviors.vaGovPreventSelectDuplicates = {
    attach: function attach(context) {
      if (servicesFieldset) {
        servicesFieldset.addEventListener("change", winnower(context));
      }
    }
  };
})(Drupal);