/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }

(function ($, Drupal) {
  Drupal.behaviors.vaGovSetServiceSelects = {
    attach: function attach(context) {
      var adminRoles = ["content_admin", "administrator"];

      $(context).ajaxComplete(function () {
        var vcSection = context.getElementById("edit-field-administration");

        var vcSectionValue = vcSection.options[vcSection.selectedIndex].text;

        var vcSectionValueCleaned = vcSectionValue.replace(/^(---)/, "").replace(/^(--)/, "").replace(/^(-)/, "");

        var offices = context.querySelector(".field--type-entity-reference.field--name-field-office select");

        var admins = context.querySelector(".field--type-entity-reference.field--name-field-administration select");
        var allOffices = context.querySelectorAll(".field--type-entity-reference.field--name-field-health-services .field--type-entity-reference.field--name-field-office");
        var allAdmins = context.querySelectorAll(".field--type-entity-reference.field--name-field-health-services .field--type-entity-reference.field--name-field-administration");

        if (adminRoles.some(function (item) {
          return drupalSettings.gtm_data.userRoles.includes(item);
        }) && allOffices && allAdmins) {
          allOffices.forEach(function (office) {
            office.style.display = "none";
          });
          allAdmins.forEach(function (admin) {
            admin.style.display = "none";
          });
        }

        if (offices) {
          offices.selectedIndex = [].concat(_toConsumableArray(offices.options)).findIndex(function (option) {
            return option.text === vcSectionValueCleaned;
          });
        }
        if (admins) {
          admins.selectedIndex = [].concat(_toConsumableArray(admins.options)).findIndex(function (option) {
            return option.text === vcSectionValue;
          });
        }
      });
    }
  };
})(jQuery, Drupal);