<?php

/**
 * @file
 * Contains post_api.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert().
 *
 * Queues new items for sync.
 */
function post_api_entity_insert(EntityInterface $entity) {
  _post_api_add_facility_status_to_queue($entity);
  _post_api_add_facility_service_to_queue($entity);

}

/**
 * Implements hook_entity_update().
 *
 * Queues updated items for sync.
 */
function post_api_entity_update(EntityInterface $entity) {
  _post_api_add_facility_status_to_queue($entity);
  _post_api_add_facility_service_to_queue($entity);
}

/**
 * Adds facility data to Post API queue.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   Entity.
 *
 * @return int
 *   The count of the number of items queued.
 */
function _post_api_add_facility_status_to_queue(EntityInterface $entity) {
  $facilitiesWithStatus = [
    'health_care_local_facility',
    'nca_facility',
    'vba_facility',
    'vet_center',
    'vet_center_outstation',
  ];
  if (in_array($entity->bundle(), $facilitiesWithStatus)) {
    return Drupal::service('va_gov_post_api.queue_facility_status_updates')->queueFacilityStatus($entity);
  }
  elseif ($entity->bundle() === 'health_care_region_page') {
    return Drupal::service('va_gov_post_api.queue_facility_status_updates')->queueSystemRelatedFacilities($entity);
  }

  return 0;
}

/**
 * Adds facility service data to Post API queue to update Lighthouse.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   Entity.
 *
 * @return int
 *   The count of the number of items queued.
 */
function _post_api_add_facility_service_to_queue(EntityInterface $entity) {
  if ($entity->bundle() === 'health_care_local_health_service') {
    return Drupal::service('va_gov_post_api.queue_service_updates')->queueFacilityService($entity);
  }
  elseif ($entity->bundle() === 'health_care_service_taxonomy') {
    return Drupal::service('va_gov_post_api.queue_service_updates')->queueServiceTermRelatedServices($entity);
  }
  elseif ($entity->bundle() === 'regional_health_care_service_des') {
    return Drupal::service('va_gov_post_api.queue_service_updates')->queueSystemRelatedServices($entity);
  }

  return 0;
}
