#!/bin/sh

# regex to validate in commit msg
commit_regex='(VAGOV-[0-9]+)'
error_msg="Aborting commit. Your commit message is missing a Github ticket number ('VAGOV-123')"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi
