#!/usr/bin/env php
<?php
/**
 * .git/hooks/pre-commit
 *
 * This pre-commit hook will drush dcs Drupal files.
 */

echo exec('./docroot/vendor/bin/phpcs --version') . " sniffing...\n";

exec('git diff --cached --name-status --diff-filter=ACM', $output);

$status = 0;
$violations = array();

foreach ($output as $file) {

  $file_name = trim(substr($file, 1));
  $ext = pathinfo($file_name, PATHINFO_EXTENSION);

  // Don't run on features.
  if ((strpos($file_name, '.features.') !== FALSE) ||
      (strpos($file_name, '_default.inc') !== FALSE) ||
      (strpos($file_name, '/modules/contrib/') !== FALSE)) {
    print "PHP_CodeSniffer skipping " . $file_name . ".\n";
    continue;
  }

  // Hopefully, this is every Drupal extension. The Drupal code sniff seems to
  // run itself against every file, which seems unnecessary.
  $check_ext = array('php', 'module', 'install', 'test', 'inc', 'profile', 'view', 'info');
  if (in_array($ext, $check_ext)) {
    $sniff = array();
    exec('./docroot/vendor/bin/phpcs --standard=./docroot/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml ' . escapeshellarg($file_name), $sniff, $return);

    if ($return) {
      $status = 1;
      print implode("\n", $sniff) . "\n";
      $violations[] = $file_name;
    }
  }
  else {
    print "PHP_CodeSniffer is skipping " . $file_name . " because of extension.\n";
  }
}

print "PHP_CodeSniffer complete. Exit status: $status\n";

exit($status);
