# Schema for the configuration files of the VA.gov Menus Helper module.
va_gov_menus.settings:
  type: config_object
  label: 'VA.gov Menus Helper settings'
  mapping:
    example:
      type: string
      label: 'Example'
