/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  function refreshStatusBlock(url) {
    $.get(url, function (data) {
      $("#block-content-release-status-block table").html(data);
    });
  }

  Drupal.behaviors.contentReleaseStatusBlock = {
    attach: function attach(context, settings) {
      $(window, context).once("contentReleaseStatusBlock").on("load", function () {
        window.setInterval(function () {
          refreshStatusBlock(settings.contentReleaseStatusBlock.blockRefreshPath);
        }, 10000);
      });
    }
  };
})(jQuery, window.Drupal);