<?php

/**
 * @file
 * Contains va_gov_facilities.module.
 */

use Drupal\Component\Render\FormattableMarkup;
use Drupal\Core\Entity\EntityForm;
use Drupal\Core\Entity\EntityFormInterface;
use Drupal\Core\Entity\EntityInterface;

use Drupal\Core\Field\WidgetBase;
use Drupal\Core\Form\FormStateInterface;
use \Drupal\node\NodeInterface;
use Drupal\va_gov_facilities\EventSubscriber\FacilitiesSubscriber;

/**
 * @file
 * Contains va_gov_facilities.module.
 */

/**
 * Implements hook_page_attachments().
 */
function va_gov_facilities_page_attachments(array &$attachments) {
  // Control visibility/required for facility status details.
  $attachments['#attached']['library'][] = 'va_gov_facilities/facility_status_details';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function va_gov_facilities_preprocess_field__paragraph__field_hours(&$variables) {
  // The value of the "Use the facility's hours" choice.
  $use_facility_hours = "0";
  $item_list = $variables['element']['#items'];
  $paragraph = $item_list->getEntity();
  $field_name = "field_hours";
  if ($paragraph->$field_name->value === $use_facility_hours) {
    $node_parent = va_gov_backend_get_parent_node($paragraph);
    if ($node_parent) {
      $related_field = "field_facility_location";
      $field_to_render = "field_office_hours";
      $variables['actual_hours'] = FacilitiesSubscriber::createRenderArrayFromFieldOnRefdEntity($node_parent, $related_field, $field_to_render);
    }
  }
}

function _va_gov_facilities_get_service_default_appt_text(FormStateInterface $form_state) {
  $default_text = "Default text placeholder";
  /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
  $form_object = $form_state->getFormObject();
  $type = $form_object->getEntity()->getEntityType()->id();
  $bundle = $form_object->getEntity()->bundle();
  $entity = $form_object->getEntity();

  switch($bundle) {

    case 'health_care_local_health_service':
      // If the markup exists and has some markup, let's put it in the default text.
      if ($entity->field_hservices_lead_in_default && !$entity->field_hservices_lead_in_default->isEmpty()) {
        $default_text = trim(strip_tags($entity->field_hservices_lead_in_default->getFieldDefinition()->getSetting('markup')['value']));
      }
      break;

    case 'service_region':
      // If the markup exists and has some markup, let's put it in the default text.
      if ($entity->field_vba_serv_reg_appt_default && !$entity->field_vba_serv_reg_appt_default->isEmpty()) {
        $default_text = trim(strip_tags($entity->field_vba_serv_reg_appt_default->getFieldDefinition()->getSetting('markup')['value']));
      }
      break;


  }


  return $default_text;
}

function _va_gov_facilities_set_service_location_field_states() {

}

/**
 * Implements hook_field_widget_single_element_WIDGET_TYPE_form_alter().
 */
function va_gov_facilities_field_widget_single_element_paragraphs_form_alter(&$element, FormStateInterface $form_state, $context) {

  // Create the element in the form just under the field_appt_intro_text_type
      // TODO: Try to make a form that sits at weight 5 but above the Custom
      // Right now, I can't get it in the right place

      $default_text = _va_gov_facilities_get_service_default_appt_text($form_state) ?? '';
      $description = new FormattableMarkup($default_text, []);

      $element['subform']['field_appt_intro_text_type']['temp_default_text'] = [
        '#type' => 'textarea',
        '#title' => t('Default text'),
        '#value' => $description,
        '#weight' => 1,
        '#disabled' => TRUE,
      ];

  $field_definition = $context['items']->getFieldDefinition();
  /**
   * @var \Drupal\field\Entity\FieldConfig $field_definition */
  $paragraph_entity_reference_field_name = $field_definition->getName();

  $target_paragraph_ref_fields = [
    'field_service_location',
  ];

  if (in_array($paragraph_entity_reference_field_name, $target_paragraph_ref_fields)) {
    $widget_state = WidgetBase::getWidgetState($element['#field_parents'], $paragraph_entity_reference_field_name, $form_state);

    $paragraph_instance = $widget_state['paragraphs'][$element['#delta']]['entity'];
    $paragraph_type = $paragraph_instance->bundle();

    if ($paragraph_type == 'service_location') {
      // Hide Appointments Custom text unless explicitly selected.
      $selector = sprintf(':input[name="%s[%d][subform][%s]"]', $paragraph_entity_reference_field_name, $element['#delta'], 'field_appt_intro_text_type');

      $element['subform']['field_appt_intro_text_custom']['#states'] = [
        'visible' => [
          $selector => ['value' => 'customize_text'],
        ],
      ];
      $element['subform']['field_appt_intro_text_type']['temp_default_text']['#states'] = [
        'visible' => [
          $selector => ['value' => 'use_default_text'],
        ],
      ];



      // Atta
      // $attachments['#attached']['drupalSettings']['appt-default-text'] = _va_gov_facilities_appt_default_text();

    }
  }



}
