version: 1
update_configs:
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "security"
# va-gov/web fails because dependabot can't deal with composer git packages right now
# Follow the trail starting here and fix https://github.com/department-of-veterans-affairs/va.gov-cms/issues/910
# Then we can uncomment the below and get daily updates auto-merged on test passes. 
#       - match:
#           dependency_name: "va-gov/web"
#     automerged_updates:
#       - match:
#           dependency_name: "va-gov/web"
