version: 1
update_configs:
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "security"
      - match:
          dependency_name: "va-gov/web"
    automerged_updates:
      - match:
          dependency_name: "va-gov/web"
