@api
Feature: Content model
  In order to enter structured content into my site
  As a content editor
  I want to have content entity types that reflect my content model.

  @spec @content_type
  Scenario: Bundles
    Then exactly the following content entity type bundles should exist
      | Name                    | Machine name            | Type              | Description                                                                      |
      | Basic page              | page                    | Content type      | Use <em>basic pages</em> for your static content, such as an 'About us' page.    |
      | Hub landing page        | landing_page            | Content type      | A special page with its own one-off layout and content.                          |
      | Support Service         | support_service         | Content type      | Help desks, hotlines, etc, to be contextually placed alongside relevant content. |
      | Audio file              | audio_file              | Media type        | A locally hosted audio file, such as an MP3.                                     |
      | Document                | document                | Media type        | A locally hosted document, such as a PDF.                                        |
      | Image                   | image                   | Media type        | Locally hosted images.                                                           |
      | Video                   | video                   | Media type        | A video hosted by YouTube, Vimeo, or some other provider.                        |
      | Video file              | video_file              | Media type        | A locally hosted video file                                                      |
      | Accordion               | collapsible_panel       | Paragraph type    | A group of accordions.                                                           |
      | Accordion Item          | collapsible_panel_item  | Paragraph type    | An individual accordion.                                                         |
      | Alert Paragraph         | alert                   | Paragraph type    | Create 8 different styles of alert boxes for VA.gov                              |
      | Expandable Text         | expandable_text         | Paragraph type    | Text that expands upon click.                                                    |
      | Link teaser             | link_teaser             | Paragraph type    | A link followed by a description. For building inline "menus" of content.        |
      | List of link teasers    | list_of_link_teasers    | Paragraph type    | A paragraph that contains only one type of paragraph: Link teaser.               |
      | Process                 | process                 | Paragraph type    | An ordered list (1, 2, 3, 4, N) of steps in a process.                           |
      | Q&A                     | q_a                     | Paragraph type    | Question and Answer                                                              |
      | Q&A Section             | q_a_section             | Paragraph type    | A set of questions and answers with optional header.                             |
      | Starred Horizontal Rule | starred_horizontal_rule | Paragraph type    |                                                                                  |
      | WYSIWYG                 | wysiwyg                 | Paragraph type    | An open-ended text field.                                                        |
      | Alert                   | alert                   | Custom block type | An alert box that can be added to individual pages.                              |
      | Address                 | address                 | Paragraph type    | An address block                                                                 |
      | React Widget            | react_widget            | Paragraph type    | Add a React component to this page.                                              |
      | Administration          | administration          | Vocabulary        | Represents a hierarchy of the VA, partly for governance purposes.                |
      | Promo                   | promo                   | Custom block type | Promote a link with an image, title, and description.                            |

  @spec @field_type
  Scenario: Fields
    Then exactly the following fields should exist
      | Type              | Bundle               | Field label                                  | Machine name                     | Field type                 | Required | Cardinality | Form widget                       | Translatable | Help text                                                                                                                                                                                                                                                                               |
      | Content type      | Basic page           | Alert                                        | field_alert                      | Entity reference           |          | 1           | Select list                       |              | [Help text here]                                                                                                                                                                                                                                                                        |
      | Content type      | Basic page           | Meta tags                                    | field_meta_tags                  | Meta tags                  |          | 1           | Advanced meta tags form           |              |                                                                                                                                                                                                                                                                                         |
      | Media type        | Document             | Document                                     | field_document                   | File                       |          | 1           | File                              |              |                                                                                                                                                                                                                                                                                         |
      | Media type        | Image                | Image                                        | image                            | Image                      | Required | 1           | ImageWidget crop                  |              |                                                                                                                                                                                                                                                                                         |
      | Media type        | Video                | Video URL                                    | field_media_video_embed_field    | Video Embed                | Required | 1           | Video Textfield                   | Translatable |                                                                                                                                                                                                                                                                                         |
      | Media type        | Audio file           | Audio file                                   | field_media_audio_file           | File                       | Required | 1           | File                              | Translatable |                                                                                                                                                                                                                                                                                         |
      | Media type        | Audio file           | Show in media library                        | field_media_in_library           | Boolean                    |          | 1           | Single on/off checkbox            | Translatable |                                                                                                                                                                                                                                                                                         |
      | Media type        | Document             | Show in media library                        | field_media_in_library           | Boolean                    |          | 1           | Single on/off checkbox            | Translatable |                                                                                                                                                                                                                                                                                         |
      | Media type        | Image                | Show in media library                        | field_media_in_library           | Boolean                    |          | 1           | Single on/off checkbox            |              |                                                                                                                                                                                                                                                                                         |
      | Media type        | Video                | Show in media library                        | field_media_in_library           | Boolean                    |          | 1           | Single on/off checkbox            | Translatable |                                                                                                                                                                                                                                                                                         |
      | Media type        | Video file           | Show in media library                        | field_media_in_library           | Boolean                    |          | 1           | Single on/off checkbox            | Translatable |                                                                                                                                                                                                                                                                                         |
      | Media type        | Video file           | Video file                                   | field_media_video_file           | File                       | Required | 1           | File                              | Translatable |                                                                                                                                                                                                                                                                                         |
      | Content type      | Basic page           | Related Links                                | field_related_links              | Entity reference revisions |          | 1           | Paragraphs EXPERIMENTAL           |              | [Some help text]                                                                                                                                                                                                                                                                        |
      | Content type      | Basic page           | Last Update                                  | field_last_update                | Date                       |          | 1           | Date and time                     |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Alert Paragraph      | Alert Heading                                | field_alert_heading              | Text (plain)               | Required | 1           | Textfield                         |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Alert Paragraph      | Alert Type                                   | field_alert_type                 | List (text)                | Required | 1           | Select list                       |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Alert Paragraph      | Alert Message                                | field_alert_message              | Text (formatted, long)     | Required | 1           | Text area (multiple rows)         |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Alert Paragraph      | Trigger Text                                 | field_alert_trigger_text         | Text (plain)               |          | 1           | Textfield                         |              | The text that users will click to expand alert box and display message.                                                                                                                                                                                                                 |
      | Paragraph type    | Accordion            | Allow more than one item to expand at a time | field_collapsible_panel_multi    | Boolean                    |          | 1           | Single on/off checkbox            |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Accordion            | Collapsible Panel Items                      | field_va_paragraphs              | Entity reference revisions | Required | Unlimited   | Paragraphs Classic                | Translatable |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Accordion            | Add border around items                      | field_collapsible_panel_bordered | Boolean                    |          | 1           | Single on/off checkbox            |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Accordion            | Start expanded                               | field_collapsible_panel_expand   | Boolean                    |          | 1           | Single on/off checkbox            |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Expandable Text      | Full Text                                    | field_wysiwyg                    | Text (formatted, long)     | Required | 1           | Text area (multiple rows)         | Translatable |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Expandable Text      | Text Expander                                | field_text_expander              | Text (plain)               | Required | 1           | Textfield                         |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Link teaser          | Link                                         | field_link                       | Link                       |          | 1           | Link                              |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | List of link teasers | Link teasers                                 | field_va_paragraphs              | Entity reference revisions |          | Unlimited   | Paragraphs Classic                | Translatable |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | List of link teasers | Title                                        | field_title                      | Text (plain)               |          | 1           | Textfield                         | Translatable |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | WYSIWYG              | Text                                         | field_wysiwyg                    | Text (formatted, long)     |          | 1           | Text area (multiple rows)         | Translatable |                                                                                                                                                                                                                                                                                         |
      | Content type      | Support Service      | Phone Number                                 | field_phone_number               | Telephone number           |          | 1           | Telephone number                  |              |                                                                                                                                                                                                                                                                                         |
      | Content type      | Support Service      | Link                                         | field_link                       | Link                       |          | 1           | Link                              |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Q&A                  | Question                                     | field_question                   | Text (plain)               | Required | 1           | Textfield                         |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Q&A                  | Answer                                       | field_answer                     | Entity reference revisions | Required | Unlimited   | Paragraphs EXPERIMENTAL           |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Q&A Section          | Section Header                               | field_section_header             | Text (plain)               |          | 1           | Textfield                         |              | An optional title that groups multiple questions together.                                                                                                                                                                                                                              |
      | Paragraph type    | Q&A Section          | Questions                                    | field_questions                  | Entity reference revisions | Required | Unlimited   | Paragraphs Classic                |              |                                                                                                                                                                                                                                                                                         |
      | Content type      | Basic page           | Description                                  | field_description                | Text (plain)               | Required | 1           | Textfield                         |              | Describe the content concisely, ideally between 120 and 158 characters. This text will appear on content listings on the site, and will describe the content in search engines, and when this content is shared on social media.                                                        |
      | Content type      | Basic page           | Featured content                             | field_featured_content           | Entity reference revisions |          | Unlimited   | Paragraphs EXPERIMENTAL           |              | Highlight the most important content on your page here, in the form of a Q&A or some text edited in a WYWSIWYG editor.                                                                                                                                                                  |
      | Content type      | Basic page           | Intro text                                   | field_intro_text                 | Text (plain, long)         | Required | 1           | Text area (multiple rows)         |              | This text appears directly beneath the page title, but may also appear as a summary of the content in other places, such as search results and social media posts.                                                                                                                      |
      | Content type      | Basic page           | Main content                                 | field_content_block              | Entity reference revisions |          | Unlimited   | Paragraphs EXPERIMENTAL           |              | [Some help text]                                                                                                                                                                                                                                                                        |
      | Content type      | Basic page           | Plainlanguage Date                           | field_plainlanguage_date         | Date                       |          | 1           | Date and time                     |              | Indicate the date this content was certified.                                                                                                                                                                                                                                           |
      | Content type      | Hub landing page     | Administration                               | field_administration             | Entity reference           |          | 1           | Select list                       |              | To which administration or office does this Hub belong?                                                                                                                                                                                                                                 |
      | Content type      | Hub landing page     | Alert                                        | field_alert                      | Entity reference           |          | 1           | Select list                       | Translatable |                                                                                                                                                                                                                                                                                         |
      | Content type      | Hub landing page     | Description                                  | field_description                | Text (plain)               | Required | 1           | Textfield                         | Translatable | Describe the content concisely, ideally between 120 and 158 characters. This text will appear on content listings on the site, and will describe the content in search engines, and when this content is shared on social media.                                                        |
      | Content type      | Hub landing page     | Intro text                                   | field_intro_text                 | Text (plain, long)         | Required | 1           | Text area (multiple rows)         | Translatable | This text appears directly beneath the page title, but may also appear as a summary of the content in other places, such as search results and social media posts.                                                                                                                      |
      | Content type      | Hub landing page     | Meta tags                                    | field_meta_tags                  | Meta tags                  |          | 1           | Advanced meta tags form           | Translatable |                                                                                                                                                                                                                                                                                         |
      | Content type      | Hub landing page     | Plain language Certified Date                | field_plainlanguage_date         | Date                       |          | 1           | Date and time                     | Translatable | [Help text here]                                                                                                                                                                                                                                                                        |
      | Content type      | Hub landing page     | Related Links                                | field_related_links              | Entity reference revisions |          | 1           | Paragraphs EXPERIMENTAL           | Translatable | [Help text goes here]                                                                                                                                                                                                                                                                   |
      | Content type      | Hub landing page     | Spokes                                       | field_spokes                     | Entity reference revisions | Required | 4           | Paragraphs EXPERIMENTAL           |              | [Help text goes here]                                                                                                                                                                                                                                                                   |
      | Custom block type | Promo                | Image                                        | field_image                      | Entity reference           | Required | 1           | Entity browser                    |              |                                                                                                                                                                                                                                                                                         |
      | Custom block type | Promo                | Link                                         | field_promo_link                 | Entity reference revisions |          | 1           | Paragraphs Classic                |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Accordion Item       | Text                                         | field_wysiwyg                    | Text (formatted, long)     |          | 1           | Text area (multiple rows)         | Translatable |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Accordion Item       | Title                                        | field_title                      | Text (plain)               | Required | 1           | Textfield                         | Translatable |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Address              | Address                                      | field_address                    | Address                    |          | 1           | Address                           |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Process              | Steps                                        | field_steps                      | Text (formatted, long)     | Required | Unlimited   | Text area (multiple rows)         |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | React Widget         | Custom React Root                            | field_custom_react_root          | Boolean                    |          | 1           | Single on/off checkbox            |              | If true adds a div with the id "react-root" to this page.                                                                                                                                                                                                                               |
      | Paragraph type    | React Widget         | In Maintenance                               | field_in_maintenance             | Boolean                    |          | 1           | Single on/off checkbox            |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | React Widget         | Maintenance Line 1                           | field_maintenance_line_1         | Text (plain, long)         |          | 1           | Text area (multiple rows)         |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | React Widget         | Maintenance Line 2                           | field_maintenance_line_2         | Text (plain, long)         |          | 1           | Text area (multiple rows)         |              |                                                                                                                                                                                                                                                                                         |
      | Vocabulary        | Administration       | Acronym                                      | field_acronym                    | Text (plain)               |          | 1           | Textfield                         |              | Eg VHA, VBA, NCA, OPIA, OIT, etc                                                                                                                                                                                                                                                        |
      | Vocabulary        | Administration       | Description                                  | field_description                | Text (plain)               | Required | 1           | Textfield                         |              | Describe the content concisely, ideally between 120 and 158 characters. This text will appear on content listings on the site, and will describe the content in search engines, and when this content is shared on social media.                                                        |
      | Vocabulary        | Administration       | Intro text                                   | field_intro_text                 | Text (plain, long)         | Required | 1           | Text area (multiple rows)         |              | [Help text here]                                                                                                                                                                                                                                                                        |
      | Vocabulary        | Administration       | Link                                         | field_link                       | Link                       |          | 1           | Link                              |              | The URL for the legacy landing page for this office, if it's not the page you're currently creating/editing.                                                                                                                                                                            |
      | Vocabulary        | Administration       | Link text                                    | field_email_updates_link_text    | Text (plain)               |          | 1           | Textfield                         |              |                                                                                                                                                                                                                                                                                         |
      | Vocabulary        | Administration       | Metatags                                     | field_metatags                   | Meta tags                  |          | 1           | Advanced meta tags form           |              |                                                                                                                                                                                                                                                                                         |
      | Vocabulary        | Administration       | Social media links                           | field_social_media_links         | Social Media Links Field   |          | 1           | List with all available platforms |              |                                                                                                                                                                                                                                                                                         |
      | Vocabulary        | Administration       | Support services                             | field_support_services           | Entity reference           |          | Unlimited   | Inline entity form - Complex      |              |                                                                                                                                                                                                                                                                                         |
      | Vocabulary        | Administration       | URL                                          | field_email_updates_url          | Text (plain)               |          | 1           | Textfield                         |              | Starting with https://                                                                                                                                                                                                                                                                  |
      | Content type      | Basic page           | Page last built                              | field_page_last_built            | Date                       |          | 1           | Date and time                     |              |                                                                                                                                                                                                                                                                                         |
      | Content type      | Hub landing page     | Page last built                              | field_page_last_built            | Date                       |          | 1           | Date and time                     | Translatable |                                                                                                                                                                                                                                                                                         |
      | Content type      | Hub landing page     | Promo                                        | field_promo                      | Entity reference           |          | 1           | Select list                       |              |                                                                                                                                                                                                                                                                                         |
      | Custom block type | Alert                | Crisis Alert Answer                          | field_alert_content              | Entity reference revisions | Required | 1           | Paragraphs Classic                |              | Remember that this content is for people in crisis: be simple and straighforward.<br /><ul><li>Give a single clear next step</li><li>Highlight the <strong>most important information</strong> in bold</li><li>Link to an additional page if there's more information to share</li><ul> |
      | Content type      | Hub landing page     | Support Services                             | field_support_services           | Entity reference           |          | Unlimited   | Inline entity form - Complex      |              | [Help text goes here]                                                                                                                                                                                                                                                                   |
      | Content type      | Support Service      | Page last built                              | field_page_last_built            | Date                       |          | 1           | Date and time                     | Translatable |                                                                                                                                                                                                                                                                                         |
      | Custom block type | Alert                | Alert Type                                   | field_alert_type                 | List (text)                | Required | 1           | -- Disabled --                    |              |                                                                                                                                                                                                                                                                                         |
      | Custom block type | Alert                | Crisis Alert Question                        | field_alert_title                | Text (plain)               | Required | 1           | Textfield                         |              | This should be a first-person question: "How can I _____?" or "How do I _____?"                                                                                                                                                                                                         |
      | Custom block type | Alert                | Crisis alerts look like                      | field_content_preview            | Markup                     |          | 1           | Markup                            |              |                                                                                                                                                                                                                                                                                         |
      | Custom block type | Alert                | General help text                            | field_help_text                  | Markup                     |          | 1           | Markup                            |              |                                                                                                                                                                                                                                                                                         |
      | Custom block type | Alert                | Owner                                        | field_owner                      | Entity reference           |          | 1           | Client-side hierarchical select   |              |                                                                                                                                                                                                                                                                                         |
      | Custom block type | Alert                | Reusability                                  | field_reusability                | List (text)                | Required | 1           | Check boxes/radio buttons         |              |                                                                                                                                                                                                                                                                                         |
      | Paragraph type    | Link teaser          | Link summary                                 | field_link_summary               | Text (plain)               |          | 1           | Textfield                         |              | A short description of the link, less than 500 characters.                                                                                                                                                                                                                              |
      | Paragraph type    | React Widget         | Custom React Root                            | field_custom_react_root          | Boolean                    |          | 1           | Single on/off checkbox            |              | If true adds a div with the id "react-root" to this page.                                                                                                                                                                                                                               |
