field.storage_settings.magichead:
  type: field.storage_settings.entity_reference_revisions

field.widget.settings.magichead_paragraphs_classic:
  type: mapping
  mapping:
    title:
      type: label
    title_plural:
      type: label
    edit_mode:
      type: string
    add_mode:
      type: string
    form_display_mode:
      type: string
    default_paragraph_type:
      type: string
    max_depth:
      type: integer
