cd ../READMES/openapi
sed -i 's/block_content--alert/BlockContentAlert/g' openapi_no_relationships.yaml
sed -i 's/block_content--promo/BlockContentPromo/g' openapi_no_relationships.yaml
sed -i 's/file--file/FileFile/g' openapi_no_relationships.yaml
sed -i 's/links_metadata/LinksMetadata/g' openapi_no_relationships.yaml
sed -i 's/list_metadata/ListMetadata/g' openapi_no_relationships.yaml
sed -i 's/media--image/MediaImage/g' openapi_no_relationships.yaml
sed -i 's/node--banner/NodeBanner/g' openapi_no_relationships.yaml
sed -i 's/node--checklist/NodeChecklist/g' openapi_no_relationships.yaml
sed -i 's/node--documentation_page/NodeDocumentationPage/g' openapi_no_relationships.yaml
sed -i 's/node--faq_multiple_q_a/NodeFaqMultipleQA/g' openapi_no_relationships.yaml
sed -i 's/node--full_width_banner_alert/NodeFullWidthBannerAlert/g' openapi_no_relationships.yaml
sed -i 's/node--landing_page/NodeLandingPage/g' openapi_no_relationships.yaml
sed -i 's/node--media_list_image/NodeMediaListImage/g' openapi_no_relationships.yaml
sed -i 's/node--media_list_videos/NodeMediaListVideos/g' openapi_no_relationships.yaml
sed -i 's/node--office/NodeOffice/g' openapi_no_relationships.yaml
sed -i 's/node--q_a/NodeQA/g' openapi_no_relationships.yaml
sed -i 's/node--step_by_step/NodeStepByStep/g' openapi_no_relationships.yaml
sed -i 's/node--support_resources_detail_page/NodeSupportResourcesDetailPage/g' openapi_no_relationships.yaml
sed -i 's/node--support_service/NodeSupportService/g' openapi_no_relationships.yaml
sed -i 's/paragraph--alert_single/ParagraphAlertSingle/g' openapi_no_relationships.yaml
sed -i 's/paragraph--audience_topics/ParagraphAudienceTopics/g' openapi_no_relationships.yaml
sed -i 's/paragraph--checklist/ParagraphChecklist/g' openapi_no_relationships.yaml
sed -i 's/paragraph--contact_information/ParagraphContactInformation/g' openapi_no_relationships.yaml
sed -i 's/paragraph--email_contact/ParagraphEmailContact/g' openapi_no_relationships.yaml
sed -i 's/paragraph--expandable_text/ParagraphExpandableText/g' openapi_no_relationships.yaml
sed -i 's/paragraph--link_teaser/ParagraphLinkTeaser/g' openapi_no_relationships.yaml
sed -i 's/paragraph--list_of_link_teasers/ParagraphListOfLinkTeasers/g' openapi_no_relationships.yaml
sed -i 's/paragraph--media_list_images/ParagraphMediaListImages/g' openapi_no_relationships.yaml
sed -i 's/paragraph--media_list_videos/ParagraphMediaListVIdeos/g' openapi_no_relationships.yaml
sed -i 's/paragraph--non_reusable_alert/ParagraphNonReusableAlert/g' openapi_no_relationships.yaml
sed -i 's/paragraph--phone_number/ParagraphPhoneNumber/g' openapi_no_relationships.yaml
sed -i 's/paragraph--rich_text_char_limit_1000/ParagraphRichTextCharLimit1000/g' openapi_no_relationships.yaml
sed -i 's/paragraph--wysiwyg/ParagraphWYSIWYG/g' openapi_no_relationships.yaml
sed -i 's/taxonomy_term--administration/TaxonomyTermAdministration/g' openapi_no_relationships.yaml
sed -i 's/taxonomy_term--audience_beneficiaries/TaxonomyTermAudienceBeneficiaries/g' openapi_no_relationships.yaml
sed -i 's/taxonomy_term--audience_non_beneficiaries/TaxonomyTermNonBeneficiaries/g' openapi_no_relationships.yaml
sed -i 's/taxonomy_term--lc_categories/TaxonomyTermLCCategories/g' openapi_no_relationships.yaml
sed -i 's/taxonomy_term--products/TaxonomyTermProducts/g' openapi_no_relationships.yaml
sed -i 's/user--user/UserUser/g' openapi_no_relationships.yaml
sed -i 's/jsonapi_metadata/JsonAPIMetadata/g' openapi_no_relationships.yaml
sed -i 's/application\/json/application\/vnd.api+json/g' openapi_no_relationships.yaml
