#!/bin/sh
# Run with ./scripts/generate-open-spec.sh https://<your-domain>
set -e;

url="$1/openapi/va_gov?_format=json";
tmp_name=$(mktemp)
wget --output-document="${tmp_name}" "${url}"
swagger2openapi -y -o=openapi_autogenerated.yaml $tmp_name
mv openapi_autogenerated.yaml "./READMES/openapi/"
