<?php

/**
 * @file
 * Contains va_gov_login.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function va_gov_login_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Always recolor submit button & hide pass helptext.
  $form['actions']['submit']['#attributes']['class'][] = 'button--primary';
  unset($form['pass']['#description']);
  unset($form['pass']['description']);

  // Create PIV login & container.
  $form['samlauth_login_link'] = [
    '#type' => 'fieldset',
    '#title' => 'PIV login',
    '#title_display' => 'invisible',
    '#weight' => -1,
    '#attributes' => [
      'class' => ['piv-container', 'js-piv-container'],
    ],
  ];
  $form['samlauth_login_link']['link'] = [
    '#title' => 'Log in with PIV',
    '#type' => 'link',
    '#url' => Url::fromRoute('samlauth.saml_controller_login'),
    '#attributes' => [
      'title' => 'Follow this link to login using your PIV or other smartcard.',
      'class' => ['samlauth-login-link', 'button', 'button--primary'],
    ],
  ];

  // Modify existing text and add classes for JS toggle & styles.
  $form['name']['#description'] = 'Your VA email address';
  $form['name']['#prefix'] = '<div class="password-prefix form-item__description">Only use this method if you\'ve already been approved to use password log in. If you\'re not sure, try <a href="/user/login">logging in with PIV first</a> or <a href="https://va-gov.atlassian.net/servicedesk/customer/portal/3/group/8/create/26">contact the CMS help desk.</a></div>';
  $form['name']['#wrapper_attributes']['class'][] = 'js-login-username';
  $form['pass']['#wrapper_attributes']['class'][] = 'js-login-password';
  $form['actions']['submit']['#attributes']['class'][] = 'js-login-submit';

  // Create help link & form toggle.
  $form['#suffix'] = '<div class="suffix-links"><a href="/help/cms-basics/how-to-log-inout">Get help</a></div>';
  $form['actions']['toggle'] = [
    '#type' => 'button',
    '#button_type' => 'toggle',
    '#attributes' => [
      'class' => [
        'link',
        'va-login-toggle',
        'js-va-login-toggle',
      ],
    ],
    '#value' => 'Developer log in',
  ];

  // Check user input to determine if form is being rebuilt with error.
  $user_input = $form_state->getUserInput();
  if (isset($user_input['name']) || isset($user_input['pass'])) {
    $form['#attributes']['class'][] = 'form-login';
    $form['actions']['toggle']['#value'] = 'Log in with PIV';
  }
  else {
    $form['#attributes']['class'][] = 'piv-login';
  }

  // Attach JS library for toggle button.
  $form['#attached']['library'][] = 'va_gov_login/login-toggle';
}
