<?php

/**
 * @file
 * Contains va_gov_login.module.
 */

use Drupal\Core\Field\FieldFilteredMarkup;
use Drupal\Component\Render\FormattableMarkup;

/**
 * Implements hook_form_alter().
 */
function va_gov_login_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "user_login_form") {
    $form['pass']["#description"] = FieldFilteredMarkup::create(t('Enter the password that accompanies your username, if you have an issue with your password please email the @helpdesk.', ['@helpdesk' => new FormattableMarkup('<a href="mailto:vacmssupport@va.gov">helpdesk</a>', [])]));
  }
}

/**
 * Implements hook_simplesamlphp_auth_existing_user().
 *
 * @see hook_simplesamlphp_auth_existing_user()
 */
function va_gov_login_simplesamlphp_auth_existing_user($attributes) {
  $saml_mail = $attributes['adEmail'];
  $existing_users = \Drupal::service('entity.manager')->getStorage('user')->loadByProperties(['mail' => $saml_mail]);
  if ($existing_users) {
    $existing_user = is_array($existing_users) ? reset($existing_users) : FALSE;
    if ($existing_user) {
      return $existing_user;
    }
  }
  return FALSE;
}
