<?php

/**
 * @file
 * Contains va_gov_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function va_gov_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the va_gov_content module.
    case 'help.page.va_gov_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Exported content from VA.gov') . '</p>';
      return $output;

    default:
  }
}
