#!/bin/bash

## Description: Run behat test located in ./tests/behat
## Usage: behat

set -e
export BEHAT_PARAMS='{"extensions":{"Behat\\MinkExtension":{"base_url":"http://va-gov-cms.ddev.site"},"Drupal\\DrupalExtension":{"drush":{"root":"/var/www/html/docroot","alias":"@none"},"drupal":{"drupal_root":"/var/www/html/docroot"}}}}'
export DRUPAL_ADDRESS="https://va-gov-cms.ddev.site"

cd ./tests/behat
/var/www/html/bin/behat "$@"
