#!/bin/bash

## Description: Copy migration ymls from va_gov_migrate to config/sync and run config import. Always edit in va_gov_migrate.
## Usage: migrate-sync

set -e
cp -r $DDEV_APPROOT/docroot/modules/custom/va_gov_migrate/config/install/. $DDEV_APPROOT/config/sync
$DDEV_APPROOT/bin/drush config-import -y
$DDEV_APPROOT/bin/drush config-export -y
