#!/bin/bash

## Description: Run phpcs checks against all custom code or a particular filepath
## Usage: phpcbf [TARGET]

set -e

TARGET='./docroot/modules/custom'
if [[ ! -z "${1}" ]]; then
  TARGET="${1}"
fi

./bin/phpcbf --ignore=*.md,*.min.css,styles.css,wysiwyg.css,proofing.css,user_guides.css,whats_new.css,claro.css,*/node_modules/*,*/simplesaml*/*,graphiql.css --extensions=php,module,inc,install,profile,engine,theme,css --standard=./docroot/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml --colors $TARGET
