/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(function (Drupal, once) {
  var registrationRequiredBool = document.getElementById("edit-field-event-registrationrequired-value");
  var includeRegistrationsBool = document.getElementById("edit-field-include-registration-info-value");
  var fieldAdditionalRegistrationInfo = document.getElementById("edit-field-additional-information-abo-0-value");
  var ctaSelect = document.getElementById("edit-field-event-cta");
  var fieldLinkWrapper = document.getElementById("edit-field-link-wrapper");
  var fieldLinkInput = document.getElementById("edit-field-link-0-uri");
  var fieldLinkWrapperLabel = document.querySelector("#edit-field-link-wrapper label");
  var fieldCtaEmailInput = document.getElementById("edit-field-cta-email-0-value");
  var fieldCtaEmailWrapper = document.getElementById("edit-field-cta-email-wrapper");
  var fieldCtaEmailWrapperLabel = document.querySelector("#edit-field-cta-email-wrapper label");
  var fieldCtaHowToSignUp = document.getElementById("edit-field-how-to-sign-up");
  var fieldCtaHowToSignUpWrapper = document.getElementById("edit-field-how-to-sign-up-wrapper");
  var fieldCtaHowToSignUpLabel = document.querySelector("#edit-field-how-to-sign-up-wrapper label");
  var fieldLocationTypeFacility = document.getElementById("edit-field-location-type-facility");
  var fieldLocationTypeNonFacility = document.getElementById("edit-field-location-type-non-facility");
  var includeLocationItemsRadios = document.getElementById("edit-field-location-type");
  var fieldLocationHumanreadable = document.getElementById("edit-field-location-humanreadable-0-value");
  var fieldLocationHumanreadableWrapper = document.getElementById("edit-field-location-humanreadable-wrapper");
  var targetLocationElements = document.querySelectorAll("#edit-field-facility-location-wrapper, #edit-field-url-of-an-online-event-wrapper, #edit-field-location-humanreadable-wrapper, #edit-field-address-wrapper");
  var fieldFacilityLocationWrapper = document.getElementById("edit-field-facility-location-wrapper");
  var fieldFacilityLocation = document.getElementById("edit-field-facility-location-0-target-id");
  var fieldFacilityLocationLabel = document.querySelector("label[for='edit-field-facility-location-0-target-id']");
  var fieldLocationTypeOnline = document.getElementById("edit-field-location-type-online");
  var fieldAddressWrapper = document.getElementById("edit-field-address-wrapper");
  var fieldUrlOfOnlineEvent = document.getElementById("edit-field-url-of-an-online-event-0-uri");
  var fieldUrlOfOnlineEventWrapper = document.getElementById("edit-field-url-of-an-online-event-wrapper");
  var fieldAddressLine1 = document.getElementById("edit-field-address-0-address-address-line1");
  var fieldAddressLine1Label = document.querySelector("label[for='edit-field-address-0-address-address-line1']");
  var fieldAddressLine2 = document.getElementById("edit-field-address-0-address-address-line2");
  var fieldAddressLocality = document.getElementById("edit-field-address-0-address-locality");
  var fieldAddressLocalityLabel = document.querySelector("label[for='edit-field-address-0-address-locality']");
  var fieldAddressAdminArea = document.getElementById("edit-field-address-0-address-administrative-area");
  var fieldAddressAdminAreaLabel = document.querySelector("label[for='edit-field-address-0-address-administrative-area']");
  var targetRegistrationElements = document.querySelectorAll(".centralized.reduced-padding, #edit-field-event-registrationrequired-wrapper, #edit-field-event-cta-wrapper, #edit-group-registration-link, #group-registration-link, #edit-field-additional-information-abo-wrapper");
  var safeValue = function safeValue(el) {
    var val = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : "";
    if (el) {
      el.value = val;
    }
  };
  var safeDisplay = function safeDisplay(el, display) {
    if (el) {
      el.style.display = display;
    }
  };
  var clearAdditionalRegistrationInfo = function clearAdditionalRegistrationInfo() {
    var el = fieldAdditionalRegistrationInfo;
    if (!el) {
      return;
    }
    var ckId = el.getAttribute("data-ckeditor5-id");
    if (ckId && Drupal.CKEditor5Instances && typeof Drupal.CKEditor5Instances.get === "function") {
      var editor = Drupal.CKEditor5Instances.get(ckId);
      if (editor && typeof editor.setData === "function") {
        editor.setData("");
        return;
      }
    }
    el.value = "";
  };
  var toggleCtaInputRequired = function toggleCtaInputRequired(label, wrapper, input) {
    var required = arguments.length > 3 && arguments[3] !== undefined ? arguments[3] : true;
    var addRemove = required ? "add" : "remove";
    wrapper.style.display = required ? "block" : "none";
    input.required = required ? "required" : "";
    label.classList[addRemove]("js-form-required", "form-required");
  };
  var toggleAllCtaInputsRequired = function toggleAllCtaInputsRequired() {
    var required = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : true;
    toggleCtaInputRequired(fieldLinkWrapperLabel, fieldLinkWrapper, fieldLinkInput, required);
    toggleCtaInputRequired(fieldCtaEmailWrapperLabel, fieldCtaEmailWrapper, fieldCtaEmailInput, required);
    toggleCtaInputRequired(fieldCtaHowToSignUpLabel, fieldCtaHowToSignUpWrapper, fieldCtaHowToSignUp, required);
  };
  var emptyAllCtaInputs = function emptyAllCtaInputs() {
    safeValue(fieldCtaEmailInput, "");
    safeValue(fieldLinkInput, "");
    safeValue(fieldCtaHowToSignUp, "_none");
  };
  var toggleRegistrationElements = function toggleRegistrationElements() {
    var toggleVal = !!includeRegistrationsBool.checked;
    var elementDisplayStyle = "block";
    if (!toggleVal) {
      safeValue(fieldLinkInput, "");
      safeValue(fieldCtaEmailInput, "");
      safeValue(ctaSelect, "_none");
      clearAdditionalRegistrationInfo();
      elementDisplayStyle = "none";
      if (registrationRequiredBool) {
        registrationRequiredBool.checked = false;
      }
      toggleAllCtaInputsRequired(false);
    }
    targetRegistrationElements.forEach(function (element) {
      element.style.display = elementDisplayStyle;
    });
  };
  var requireCTA = function requireCTA() {
    fieldLinkWrapper.style.display = "none";
    fieldCtaEmailWrapper.style.display = "none";
    fieldCtaHowToSignUpWrapper.style.display = "none";
    if (ctaSelect.value !== "_none") {
      if (fieldCtaEmailInput.value.length > 0) {
        toggleCtaInputRequired(fieldCtaEmailWrapperLabel, fieldCtaEmailWrapper, fieldCtaEmailInput, true);
        toggleCtaInputRequired(fieldCtaHowToSignUpLabel, fieldCtaHowToSignUpWrapper, fieldCtaHowToSignUp, true);
        fieldCtaHowToSignUp.value = "email";
      } else if (fieldLinkInput.value.length > 0) {
        toggleCtaInputRequired(fieldLinkWrapperLabel, fieldLinkWrapper, fieldLinkInput, true);
        toggleCtaInputRequired(fieldCtaHowToSignUpLabel, fieldCtaHowToSignUpWrapper, fieldCtaHowToSignUp, true);
        fieldCtaHowToSignUp.value = "url";
      } else {
        toggleCtaInputRequired(fieldCtaHowToSignUpLabel, fieldCtaHowToSignUpWrapper, fieldCtaHowToSignUpWrapper);
      }
    }
    ctaSelect.addEventListener("change", function (e) {
      emptyAllCtaInputs();
      toggleAllCtaInputsRequired(false);
      if (e.target.value !== "_none") {
        toggleCtaInputRequired(fieldCtaHowToSignUpLabel, fieldCtaHowToSignUpWrapper, fieldCtaHowToSignUp);
      }
    });
    fieldCtaHowToSignUp.addEventListener("change", function (e) {
      switch (e.target.value) {
        case "url":
          fieldCtaEmailInput.value = "";
          toggleCtaInputRequired(fieldCtaEmailWrapperLabel, fieldCtaEmailWrapper, fieldCtaEmailInput, false);
          toggleCtaInputRequired(fieldLinkWrapperLabel, fieldLinkWrapper, fieldLinkInput);
          break;
        case "email":
          fieldLinkInput.value = "";
          toggleCtaInputRequired(fieldLinkWrapperLabel, fieldLinkWrapper, fieldLinkInput, false);
          toggleCtaInputRequired(fieldCtaEmailWrapperLabel, fieldCtaEmailWrapper, fieldCtaEmailInput);
          break;
        default:
          toggleCtaInputRequired(fieldLinkWrapperLabel, fieldLinkWrapper, fieldLinkInput, false);
          toggleCtaInputRequired(fieldCtaEmailWrapperLabel, fieldCtaEmailWrapper, fieldCtaEmailInput, false);
          fieldLinkInput.value = "";
          fieldCtaEmailInput.value = "";
          break;
      }
    });
  };
  var toggleAddressRequiredFields = function toggleAddressRequiredFields(enableDisable, addRemove) {
    if (fieldAddressLine1) {
      fieldAddressLine1.required = enableDisable;
    }
    if (fieldAddressLine1Label) {
      fieldAddressLine1Label.classList[addRemove]("form-required");
    }
    if (fieldAddressLocality) {
      fieldAddressLocality.required = enableDisable;
    }
    if (fieldAddressLocalityLabel) {
      fieldAddressLocalityLabel.classList[addRemove]("form-required");
    }
    if (fieldAddressAdminArea) {
      fieldAddressAdminArea.required = enableDisable;
    }
    if (fieldAddressAdminAreaLabel) {
      fieldAddressAdminAreaLabel.classList[addRemove]("form-required");
    }
  };
  var toggleFacilityLocationRequiredFields = function toggleFacilityLocationRequiredFields(enableDisable, addRemove) {
    if (fieldFacilityLocation) {
      fieldFacilityLocation.required = enableDisable;
    }
    if (fieldFacilityLocationLabel) {
      fieldFacilityLocationLabel.classList[addRemove]("form-required");
    }
  };
  var toggleLocationElements = function toggleLocationElements() {
    targetLocationElements.forEach(function (element) {
      element.style.display = "none";
    });
    toggleAddressRequiredFields(false, "remove");
    toggleFacilityLocationRequiredFields(false, "remove");
    if (fieldLocationTypeFacility && fieldLocationTypeFacility.checked) {
      safeDisplay(fieldFacilityLocationWrapper, "block");
      safeDisplay(fieldLocationHumanreadableWrapper, "block");
      safeValue(fieldUrlOfOnlineEvent, "");
      safeValue(fieldAddressLine1, "");
      safeValue(fieldAddressLine2, "");
      safeValue(fieldAddressLocality, "");
      safeValue(fieldAddressAdminArea, "");
      toggleFacilityLocationRequiredFields(true, "add");
    }
    if (fieldLocationTypeNonFacility && fieldLocationTypeNonFacility.checked) {
      safeDisplay(fieldLocationHumanreadableWrapper, "block");
      safeDisplay(fieldAddressWrapper, "block");
      toggleAddressRequiredFields(true, "add");
      safeValue(fieldUrlOfOnlineEvent, "");
      safeValue(fieldFacilityLocation, "");
    }
    if (fieldLocationTypeOnline && fieldLocationTypeOnline.checked) {
      safeDisplay(fieldUrlOfOnlineEventWrapper, "block");
      safeValue(fieldAddressLine1, "");
      safeValue(fieldAddressLine2, "");
      safeValue(fieldAddressLocality, "");
      safeValue(fieldAddressAdminArea, "");
      safeValue(fieldFacilityLocation, "");
      safeValue(fieldLocationHumanreadable, "");
    }
  };
  var operate = function operate() {
    requireCTA();
    includeRegistrationsBool.addEventListener("click", function () {
      toggleRegistrationElements();
    });
    toggleRegistrationElements();
    includeLocationItemsRadios.addEventListener("change", function () {
      toggleLocationElements();
    });
    toggleLocationElements();
  };
  Drupal.behaviors.vaGovEventFormHelpers = {
    attach: function attach(context) {
      once("vaGovEventFormHelpers", "#edit-field-include-registration-info-value", context).forEach(function () {
        operate();
      });
    }
  };
})(Drupal, once);