/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(function (Drupal, $, once) {
  function showColumnsForErrors(tableId) {
    var _this = this;
    var $table = $(once("magicheadTabledrag", "table#" + tableId));
    $table.find(".tabledrag-hide").css("display", "");
    $table.find(".tabledrag-handle").css("display", "none");
    $table.find(".tabledrag-has-colspan").each(function () {
      _this.colSpan += 1;
    });
  }
  Drupal.behaviors.vaGovMagicheadShowErrors = {
    attach: function attach() {
      var magicheadTables = document.querySelectorAll("div.field--type-magichead table.field-multiple-table.draggable-table") || [];
      var errors = {};
      magicheadTables.forEach(function (element) {
        var $element = $(element);
        var tableId = element.id;
        var hasError = $element.find("td .form-item--error");
        if (hasError.length > 0 && !(tableId in errors)) {
          errors[tableId] = tableId;
        }
      });
      Object.values(errors).forEach(function (value) {
        return showColumnsForErrors(value);
      });
    }
  };
})(window.Drupal, jQuery, window.once);