<?php

/**
 * @file
 * Contains va_gov_help_center.module.
 */

use Drupal\Core\Url;

// The NID of the CMS Help Center homepage.
const CMS_HELP_CENTER_HOMEPAGE_NID = 6454;

/**
 * Implements hook_toolbar().
 */
function va_gov_help_center_toolbar() {
  $items = [];

  // Adds a link to CMS help center to the top level of admin toolbar.
  $items['help-center'] = [
    '#type' => 'toolbar_item',
    '#weight' => 1,
    'tab' => [
      '#type' => 'link',
      '#url' => Url::fromRoute('entity.node.canonical', ['node' => CMS_HELP_CENTER_HOMEPAGE_NID]),
      '#title' => t('Help'),
      '#attributes' => [
        'class' => ['toolbar-icon', 'toolbar-icon-help'],
      ],
    ],
  ];

  return $items;
}

/**
 * Implements hook_page_attachments().
 */
function va_gov_help_center_page_attachments(array &$attachments) {
  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();
  $route_parameters = $route_match->getParameters()->all();
  if (_va_gov_help_center_should_attach_widget($route_name, $route_parameters)) {
    $attachments['#attached']['library'][] = 'va_gov_help_center/helpdesk-widget';
  }
}

/**
 * Should we attach the helpdesk widget?
 *
 * @param string $route_name
 *   The current route name.
 * @param array $route_parameters
 *   The parameters passed with the route.
 *
 * @return bool
 *   TRUE if we should attach the widget, otherwise FALSE.
 */
function _va_gov_help_center_should_attach_widget(string $route_name, array $route_parameters): bool {
  $unconditional_routes = [
    'system.403',
    'user.login',
  ];
  if (in_array($route_name, $unconditional_routes)) {
    return TRUE;
  }
  if ($route_name === 'entity.node.canonical' && !empty($route_parameters['node']) && $node = $route_parameters['node']) {
    // Attach Jira Service Desk widget library to all nodes of type
    // `documentation_page` with an exception of CMS Help Center homepage.
    if ($node->getType() === 'documentation_page' && $node->id() != CMS_HELP_CENTER_HOMEPAGE_NID) {
      return TRUE;
    }
  }
  return FALSE;
}
