<?php

/**
 * @file
 * Contains va_gov_lovell.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_help().
 */
function va_gov_lovell_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.va_gov_lovell':
      $text = 'Visit the <a href="https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/facilities-lovell.md">Facility Lovell README</a>';

      return "<pre>{$text}</pre>";
  }

  return NULL;
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function va_gov_lovell_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  $list_item_bundles = [
    'event',
    'news_story',
    'press_release',
  ];
  if (($entity_type->id() === 'node')
  && (in_array($bundle, $list_item_bundles))
  && (isset($fields['field_listing']))
  && (isset($fields['field_administration']))) {
    // Limit the listing selection based on section.
    $fields['field_listing']->addConstraint('LovellSectionListParity');
  }
}
