name: "VA.gov CMS Post-Checkout"
description: "Performs common operations after checking out the CMS codebase."
inputs: {}
runs:
  using: "composite"
  steps:

    - name: Get Composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Use the Composer cache, if possible
      # https://github.com/actions/cache/releases/tag/v3.0.10
      uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Setup the PHP environment
      # https://github.com/shivammathur/setup-php/releases/tag/2.21.2
      uses: shivammathur/setup-php@e04e1d97f0c0481c6e1ba40f8a538454fe5d7709
      with:
        php-version: '8.1'
        extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, gd, exif, iconv
        tools: composer:v2
        coverage: xdebug

    - name: Setup the Node environment
      # https://github.com/actions/setup-node/releases/tag/v3.6.0
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
      with:
        node-version: '18.13'

    - name: Install PHP packages via Composer
      run: composer install --no-progress --prefer-dist --optimize-autoloader
      shell: bash

    - name: Setup ReviewDog
      # https://github.com/reviewdog/action-setup/releases/tag/v1.0.3
      uses: reviewdog/action-setup@8f2ec89e6b467ca9175527d2a1641bbd0c05783b
