version: '3.6'

services:
  storybook:
    container_name: ddev-${DDEV_SITENAME}-storybook
    hostname: ${DDEV_PROJECT}-storybook
    image: node:14.17
    restart: "no"
    expose:
      - 6006
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    working_dir: /home/node/app
    volumes:
      - ../docroot/design-system:/home/node/app
    command: sh -c "yarn install && yarn storybook"
    environment:
      - VIRTUAL_HOST=va-gov-storybook.${DDEV_TLD}
      - HTTP_EXPOSE=80:6006
      - HTTPS_EXPOSE=443:6006
      - NODE_ENV=production
