<?php

/**
 * @file
 * Contains va_gov_build_trigger.module.
 */

use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function va_gov_build_trigger_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // This is our preview button on node forms.
  $host = \Drupal::request()->getHost();

  if (in_array('node_form', $form['#theme'])) {
    // Fire a submit function so we can create an entity,
    // then custom function to alter revision.
    $form['actions']['preview'] = [
      '#type' => 'submit',
      '#weight' => 10,
      '#value' => 'Preview',
      '#submit' => ['::submitForm', 'va_gov_build_trigger_form_alter_submit'],
    ];
  }
}

/**
 * Implements hook_form_alter().
 */
function va_gov_build_trigger_form_alter_submit(&$form, FormStateInterface $form_state) {

  // We want to associate our user with the revision.
  $uid = Drupal::currentUser()->id();

  // Build the revision info.
  $node = $form_state->getFormObject()->getEntity();
  $node->setNewRevision(TRUE);
  $node->revision_log = 'Created revision for node in preview';
  $node->setRevisionCreationTime(REQUEST_TIME);

  // Save it as unpublished and associate with user.
  $node->setRevisionUserId($uid);
  $node->set('moderation_state', 'draft');
  $node->save();

  // Determine the environment.
  $host = \Drupal::request()->getHost();
  switch ($host) {
    // For local dev - requires setting constant DRUPAL_DEV in
    // src/site/constants/drupals.js file in vets-website repo to local address
    // and credentials.
    case 'vagovcms.lndo.site':
      $url = 'http://localhost:3001/preview?nodeId=' . $node->id();
      break;

    case 'dev.va.agile6.com':
      $url = 'http://preview-dev.vfs.va.gov/preview?nodeId=' . $node->id();
      break;

    case 'stg.va.agile6.com':
      $url = 'http://preview-staging.vfs.va.gov/preview?nodeId=' . $node->id();
      break;

    case 'va.gov':
      $url = 'http://preview-live.vfs.va.gov/preview?nodeId=' . $node->id();
      break;

    default:
      $url = 'http://preview-live.vfs.va.gov/preview?nodeId=' . $node->id();
      break;
  }

  // Send them to the preview server.
  $response = new RedirectResponse($url);
  $response->send();
}
