on:
  workflow_run:
    workflows:
      - '**'
    types:
      - completed

jobs:
  send:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Send GitHub Actions metrics to DataDog
        uses: int128/datadog-actions-metrics@46d3f0ae7393a3763b7f135f8721d89d924f3aed # v1.158.0
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          collect-job-metrics: true
          datadog-site: ddog-gov.com
