permissions:
  contents: read

on:
  workflow_run:
    workflows:
      - '**'
    types:
      - completed

jobs:
  send:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Send GitHub Actions metrics to DataDog
        uses: int128/datadog-actions-metrics@7d2cb5801be2ac88ae3efa2adf586adf9d733e1e # v1.164.0
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          collect-job-metrics: true
          datadog-site: ddog-gov.com
