name: Build and Push Drupal Container to ECR

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-region: us-gov-west-1
          role-to-assume: ${{ vars.AWS_ASSUME_ROLE }}
          role-duration-seconds: 900
          role-session-name: vsp-vagov-next-build-githubaction

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get last Apache image tag
        id: get_last_apache_tag
        run: |
          REPO_NAME="dsva/cms-apache"
          # Get all images sorted by push date (newest first)
          LAST_TAG="1.0.0"  # Default fallback
          IMAGES_JSON=$(aws ecr describe-images --repository-name $REPO_NAME --query 'sort_by(reverse(imageDetails),& imagePushedAt)' --output json)
          SEMVER_PATTERN='^[0-9]+\.[0-9]+\.[0-9]+$'

          # Loop through images from newest to oldest to find the first tag matching semantic versioning
          echo "$IMAGES_JSON" | jq -c '.[]' | while read -r IMAGE; do
            for TAG in $(echo "$IMAGE" | jq -r '.imageTags[]? // empty'); do
              if [[ "$TAG" =~ $SEMVER_PATTERN ]]; then
                LAST_TAG="$TAG"
                echo "Found most recent semantic version tag: $LAST_TAG"
                break 2
              fi
            done
          done

          echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          provenance: false
          tags: ${{ steps.login-ecr.outputs.registry }}/dsva/cms-drupal:${{ github.sha }}
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/dsva/cms-drupal:cache
          cache-to: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=${{ steps.login-ecr.outputs.registry }}/dsva/cms-drupal:cache
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            BASE_IMAGE_TAG=${{ env.LAST_TAG }}
