name: Composer Validate
on: [pull_request]
jobs:
  composer-validate:
    name: runner / composer-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.json','**/composer.lock') }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, gd, exif, iconv
          tools: composer:v2
      - name: Run PHPStan
        run: |
          composer install
          composer validate
