name: PHP_CodeSniffer
on: [pull_request]
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/post-checkout
      - name: Run PHP_CodeSniffer and ReviewDog
        run: |
          export REVIEWDOG_GITHUB_API_TOKEN="${GITHUB_TOKEN}"
          bin/phpcs \
            --standard="${STANDARD}" \
            --extensions="${EXTENSIONS}" \
            --report="${REPORT}" \
            --ignore="${IGNORE}" \
            -q \
            ${DIRECTORIES} \
            | reviewdog \
              -name="PHP_CodeSniffer" \
              -f=checkstyle \
              -reporter=github-pr-review \
              -diff='git diff'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          STANDARD: './phpcs.xml.dist'
          EXTENSIONS: 'php,module,inc,install,profile,engine,theme,css'
          REPORT: 'checkstyle'
          IGNORE: '*.md,*.min.css,styles.css,wysiwyg.css,proofing.css,user_guides.css,whats_new.css,*/node_modules/*,*/simplesaml*/*,graphiql.css'
          DIRECTORIES: 'docroot/modules/custom docroot/themes/custom tests'
