name: PHPUnit Unit Tests
on: [pull_request]
jobs:
  phpunit:
    name: runner / phpunit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, gd, exif, iconv
          tools: composer:v2
      - name: Run PHPUnit (Unit Tests only)
        run: |
          composer install
          bin/phpunit --group unit --exclude-group disabled tests/phpunit
