name: Apply Labels, owners and reviewers to pull request.

on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    - cron: '*/10 * * * *'

jobs:
  pr-team-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"`
      - uses: harupy/auto-labeling@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label-pattern: '- \[(.*?)\] ?`(.+?)`' # matches '- [x] `label`'

  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: acq688/request-reviewer-for-team-action@1.0
        with:
          config: ".github/workflows/config/request-review-for-team.yml"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"`
