name: Apply Labels, owners and reviewers to pull request.

on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    - cron: '*/10 * * * *'

jobs:
  label: Add team labels to PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"`
      - uses: harupy/auto-labeling@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label-pattern: '- \[(.*?)\] ?`(.+?)`' # matches '- [x] `label`'
