name: Apply Labels, owners and reviewers to pull requests and issues.

on:
  issues:
    types:
      - opened
      - edited
  schedule:
    - cron: '5 * * * *'

jobs:
  pr-team-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Autolabel
        # Temporary until we get this fixed upstream or pulled into this repo.
        uses: timcosgrove/auto-labeling@ed43ee47522f3a52cb912be7dea67e185e720a8e
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          label-pattern: '- \[(.*?)\] ?`(.+?)`' # matches '- [x] `label`'
