name: Apply Labels, owners and reviewers to pull requests and issues.

on:
  issues:
    types:
      - opened
      - edited
  schedule:
    - cron: '5 * * * *'

jobs:
  pr-team-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Autolabel
        # Temporary until we get this fixed upstream or pulled into this repo.
        uses: timcosgrove/auto-labeling@937d558e37285af6ca5c5813a826cf6f0d66bf0f
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          label-pattern: '- \[(.*?)\] ?`(.+?)`' # matches '- [x] `label`'
