name: Shai-Hulud 2.0 Security Check

permissions:
  contents: read

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  security-check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: gensecaihq/Shai-Hulud-2.0-Detector@v2
        with:
          fail-on-critical: true