name: Refresh Tugboat Preview ID Cache
on:
  # Every 6 hours.
  schedule:
    - cron: '0 */6 * * *'
jobs:
  # Collects the cache keys that need to be refreshed
  dispatch_cache_keys:
    name: Dispatch Tugboat Preview ID cache keys that need to be refreshed
    runs-on: ubuntu-latest
    steps:
      - name: Cross reference open PRs against cache keys in repo
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.LABEL_API_TOKEN }}
          script: |
            const prs = await github.paginate(
              github.rest.pulls.list,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
              },
              (response) => response.data.map((pr) => pr.number)
            )

            for (const pr of prs) {
              console.log(`PR: ${pr}`)
            }

            const cacheKeys = await github.paginate(
              github.rest.actions.getActionsCacheList,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
              },
              (response) => response.data.map((cache) => cache.key)
            )

            for (const key of cacheKeys) {
              console.log(`Key: ${key}`)
            }

            for (const pr of prs) {
              if (cacheKeys.includes(`${{ runner.os }}-tugboat-preview-id-pr-${pr}`)) {
                console.log(`Need to refresh: ${pr}`)
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: `${pr}`,
                  labels: ['refresh-tugboat-cache'],
                });
              }
            }
