name: Refresh Tugboat Preview ID Cache
on:
  # UTC 0am, everyday.
  schedule:
    - cron: '0 0 * * *'
jobs:
  # Collects the cache keys that need to be refreshed
  collect_cache_keys:
    name: Collect Tugboat Preview ID cache keys that need to be refreshed
    outputs:
      matrix: ${{ steps.cache-keys.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Cross reference open PRs against cache keys in repo
        id: cache-keys
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          script: |
            const prs = await github.paginate(
              github.rest.pulls.list,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
              },
              (response) => response.data.map((pr) => pr.number)
            )

            for (const pr of prs) {
              console.log(`PR: ${pr}`)
            }

            const cacheKeys = await github.paginate(
              github.rest.actions.getActionsCacheList,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
              },
              (response) => response.data.map((cache) => cache.key)
            )

            for (const key of cacheKeys) {
              console.log(`Key: ${key}`)
            }

            const toRefresh = []
            for (const pr of prs) {
              if (cacheKeys.includes(`${{ runner.os }}-tugboat-preview-id-pr-${pr}`)) {
                console.log(`Need to refresh: ${pr}`)
                toRefresh.push(pr)
              }
            }

            const result = JSON.stringify(toRefresh)
            console.log(`Refresh Keys: ${result}`)
            return result
          result-encoding: string

  # Refresh cache for given keys
  refresh_cache:
    name: Refresh cache for given keys
    needs: [ collect_cache_keys ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.collect_cache_keys.outputs.matrix)}}
    steps:
      - name: Refresh Preview ID
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: .tugboat_preview.txt
          key: ${{ runner.os }}-tugboat-preview-id-pr-${{ matrix.value }}
      - name: Cleanup temporary file
        run: rm .tugboat_preview.txt
