version: '3.2'
services:
  ca:
    image: 'devwithlando/util:stable'
    environment:
      LANDO_CA_CERT: /certs/lndo.site.pem
      LANDO_CA_KEY: /certs/lndo.site.key
      LANDO_DOMAIN: lndo.site
      LANDO_CONFIG_DIR: $LANDO_ENGINE_CONF
      LANDO_SERVICE_TYPE: ca
      COLUMNS: 256
      TERM: xterm
    command:
      - tail
      - '-f'
      - /dev/null
    labels:
      io.lando.container: 'TRUE'
      io.lando.service-container: 'TRUE'
    volumes:
      - '$LANDO_ENGINE_SCRIPTS_DIR/setup-ca.sh:/setup-ca.sh'
      - '$LANDO_ENGINE_CONF/certs:/certs'
