/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  Drupal.behaviors.vaGovFacilityStatusDetails = {
    attach: function attach() {
      function detailsRequired(action) {
        var detailswrapper = document.querySelector(".field--name-field-operating-status-more-info");
        var label = detailswrapper.querySelector(".form-item label");
        var details = detailswrapper.querySelector(".form-item textarea");
        if (action === "yes") {
          detailswrapper.style.display = "block";
          label.classList.add("js-form-required", "form-required");
          details.classList.add("required");
          details.setAttribute("required", "required");
        } else {
          detailswrapper.style.display = "none";
          label.classList.remove("js-form-required", "form-required");
          details.classList.remove("required");
          details.removeAttribute("required");
        }
      }

      var statusradios = document.querySelectorAll(".field--name-field-operating-status-facility .form-radio");
      statusradios.forEach(function (radio) {
        if (radio.checked) {
          if (radio.value === "normal") {
            detailsRequired("no");
          } else {
            detailsRequired("yes");
          }
        }
        radio.addEventListener("click", function () {
          if (radio.checked) {
            if (radio.value === "normal") {
              detailsRequired("no");
            } else {
              detailsRequired("yes");
            }
          }
        });
      });
    }
  };
})(Drupal);