/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, window, Drupal) {
  var displayHours = function displayHours(toggle, table) {
    if (toggle.checked) {
      if (toggle.value === "0") {
        $(table).show();
      } else {
        $(table).hide();
      }
    }
  };

  Drupal.behaviors.vaGovUseFacilityHours = {
    attach: function attach(context, settings) {
      var hours = context.querySelector("[data-drupal-selector$='-subform-field-hours-wrapper-facility-hours']");
      var hoursSelectionSelector = context.querySelectorAll("[id$=-subform-field-hours] input");
      hoursSelectionSelector.forEach(function (hoursSelection) {
        window.addEventListener("load", function () {
          displayHours(hoursSelection, hours);
        });
        $(hoursSelection, context).on("click", function () {
          displayHours(hoursSelection, hours);
        });
      });
    }
  };
})(jQuery, window, Drupal);