/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, window, Drupal) {
    Drupal.behaviors.vaGovUseFacilityHours = {
        attach: function attach(context, settings) {
            var hours = context.querySelector("[data-drupal-selector$='-subform-field-hours-wrapper-facility-hours']");
            var hoursSelectionSelector = context.querySelectorAll("[id$=-subform-field-hours] input");
            hoursSelectionSelector.forEach(function (hoursSelection) {
                $(hoursSelection, context).on("click", function () {
                    var choice = hoursSelection.value;
                    if (choice == "0") {
                        $(hours).show();
                    } else {
                        $(hours).hide();
                    }
                });
            });
        }
    };
})(jQuery, window, Drupal);