<?php

/**
 * @file
 * Contains va_gov_graphql.module.
 */

use Drupal\va_gov_graphql\Access\MenuLinkContentAccessHandler;

/**
 * Implements hook_entity_type_alter().
 */
function va_gov_graphql_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  $entity_types['menu_link_content']->setAccessClass(MenuLinkContentAccessHandler::class);
}

/**
 * Implements hook_theme().
 */
function va_gov_graphql_theme($existing, $type, $theme, $path) {
  return [
    'page__va_gov_graphql_explorer' => [
      'render element' => 'elements',
      'base hook' => 'block',
    ],
  ];
}
